#ifndef __INTERFACE_USER_TYPE_ATTRIBUTES__IDL__
#define __INTERFACE_USER_TYPE_ATTRIBUTES__IDL__

#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>
#include <struct/Address.idl>
#include <array/BasicTypeArray.idl>
#include <sequence/BasicTypeSequence.idl>

#include "InterfaceBasicTypeAttributes.idl"

interface InterfaceUserTypeAttributes
{
	// Here we define interface attributes which causes the
	// generation of a pair of getter und setter methods for
	// each attribute.
	
	attribute LongType 						typedefValue;
	attribute Color 							enumValue;
	attribute Address 						structValue;
	attribute LongArray 						arrayValue;
	attribute LongSeq 						sequenceValue;
  	attribute InterfaceBasicTypeAttributes 	interfaceValue;


	// Here we define a readonly attribute which causes only a getter 
	// access method.

	readonly attribute LongType 						roTypedefValue;
	readonly attribute Color 						roEnumValue;
	readonly attribute Address 						roStructValue;
	readonly attribute LongArray 					roArrayValue;
	readonly attribute LongSeq 						roSequenceValue;
  	readonly attribute InterfaceBasicTypeAttributes 	roInterfaceValue;
};

#endif // __INTERFACE_USER_TYPE_ATTRIBUTES__IDL__
