#ifndef __INTERFACE_SUPER_TYPE_TWO__IDL__
#define __INTERFACE_SUPER_TYPE_TWO__IDL__

module america
{
  	interface InterfaceSuperTypeTwo
  	{
    		attribute long attr2;
    		long op2(in string str);
  	};

}; // /module america

#endif // __INTERFACE_SUPER_TYPE_TWO__IDL__
