#ifndef __INTERFACE_VOID_TYPE_OPERATIONS__IDL__
#define __INTERFACE_VOID_TYPE_OPERATIONS__IDL__

interface InterfaceVoidTypeOperation
{
	void f0();	
	void f1(in long p1);
	long f2();
};

#endif // __INTERFACE_VOID_TYPE_OPERATIONS__IDL__
