#ifndef __INTERFACE_EXCEPTIONS__IDL__
#define __INTERFACE_EXCEPTIONS__IDL__

module world 
{
    	interface InterfaceExceptions
    	{
		struct ErrorInfo
      	{
			long code;
			string message;
      	};

      	typedef sequence<ErrorInfo> ErrorInfoList;      	

    		exception SuperError{};
     	
     	exception FatalError
      	{
			string what;
      	};
      		
     	exception ErrorException
      	{
			ErrorInfoList info;
      	};
      	      		
		long foo(in string msg)
  			raises (SuperError, FatalError, ErrorException);  			
    	};

}; // end of module world

#endif // __INTERFACE_EXCEPTIONS__IDL__
