#ifndef __INTERFACE_ATTRIBUTE_EXCEPTIONS__IDL__
#define __INTERFACE_ATTRIBUTE_EXCEPTIONS__IDL__

#include<exception/ExceptionEmpty.idl>
#include<exception/ExceptionBasicType.idl>
#include<exception/ExceptionUserType.idl>
#include<struct/Person.idl>

interface InterfaceBasicTypeAttributes
{
    attribute long longValue
	getraises(ExceptionEmpty)
        setraises(ExceptionBasicType, ExceptionUserType);

    attribute Person structValue
        getraises(ExceptionEmpty)
        setraises(ExceptionBasicType);
};

#endif // __INTERFACE_ATTRIBUTE_EXCEPTIONS__IDL__
