#ifndef __INTERFACE_SUB_TYPE__IDL__
#define __INTERFACE_SUB_TYPE__IDL__


#include "InterfaceSuperTypeOne.idl"
#include "InterfaceSuperTypeTwo.idl"

module america
{
  	interface InterfaceSubType 
    		: europe::InterfaceSuperTypeOne, InterfaceSuperTypeTwo 
  	{
    		attribute long attr3;
    		long op3(in string str);
  	};

}; // /module america

#endif // __INTERFACE_SUB_TYPE__IDL__
