
all: idl3

idl3: 
	ccmparser InterfaceConstants.idl
	ccmparser InterfaceBasicTypeAttributes.idl
	ccmparser InterfaceUserTypeAttributes.idl
	ccmparser InterfaceBasicTypeOperations.idl
	ccmparser InterfaceUserTypeOperations.idl
	ccmparser InterfaceOperationExceptions.idl
	ccmparser InterfaceSubType.idl
