module world 
{

  interface IFace
  {
    long op1(in string str);
  };
      
  component Test
  {
    uses IFace port;
  };
      
  home TestHome manages Test
  {
  };
  
}; // end of module world
