package ccmtools.generator.java.templates;

import ccmtools.generator.java.metamodel.*;

public class ArrayDefCorbaConverterTemplate
{
  protected static String nl;
  public static synchronized ArrayDefCorbaConverterTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    ArrayDefCorbaConverterTemplate result = new ArrayDefCorbaConverterTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * DO NOT EDIT!" + NL + " */" + NL + " " + NL + "package ";
  protected final String TEXT_3 = ";" + NL + "" + NL + "import ccm.local.CorbaConverterException;" + NL + "" + NL + "public class ";
  protected final String TEXT_4 = "CorbaConverter" + NL + "{" + NL + "    /** Convert a local Java type into a CORBA type */" + NL + "    public static ";
  protected final String TEXT_5 = " convert(";
  protected final String TEXT_6 = " in)" + NL + "       throws CorbaConverterException" + NL + "    {";
  protected final String TEXT_7 = NL + "        ";
  protected final String TEXT_8 = " out = new ";
  protected final String TEXT_9 = ";" + NL + "        for(int i = 0; i< in.length; i++)" + NL + "        {" + NL + "            out[i] = ";
  protected final String TEXT_10 = "(in[i]);" + NL + "        }" + NL + "        return out;" + NL + "    }" + NL + "" + NL + "" + NL + "    /** Convert a CORBA type into a local Java type */" + NL + "    public static ";
  protected final String TEXT_11 = " convert(";
  protected final String TEXT_12 = " in)" + NL + "       throws CorbaConverterException" + NL + "    {";
  protected final String TEXT_13 = NL + "        ";
  protected final String TEXT_14 = " out = new ";
  protected final String TEXT_15 = "; " + NL + "        for(int i = 0; i< in.length;i++)" + NL + "        {" + NL + "            out[i] = ";
  protected final String TEXT_16 = "(in[i]);" + NL + "        }" + NL + "        return out;" + NL + "    }" + NL + "};";
  protected final String TEXT_17 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
     ArrayDef array = (ArrayDef) argument;  
    stringBuffer.append(TEXT_1);
    stringBuffer.append(array.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(array.generateJavaRemoteNamespace());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(array.getIdentifier());
    stringBuffer.append(TEXT_4);
    stringBuffer.append(array.generateCorbaMapping());
    stringBuffer.append(TEXT_5);
    stringBuffer.append(array.generateJavaMapping());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(array.generateCorbaMapping());
    stringBuffer.append(TEXT_8);
    stringBuffer.append(array.generateCorbaMappingImpl());
    stringBuffer.append(TEXT_9);
    stringBuffer.append(array.getType().generateCorbaConverterType());
    stringBuffer.append(TEXT_10);
    stringBuffer.append(array.generateJavaMapping());
    stringBuffer.append(TEXT_11);
    stringBuffer.append(array.generateCorbaMapping());
    stringBuffer.append(TEXT_12);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(array.generateJavaMapping());
    stringBuffer.append(TEXT_14);
    stringBuffer.append(array.generateJavaMappingImpl());
    stringBuffer.append(TEXT_15);
    stringBuffer.append(array.getType().generateCorbaConverterType());
    stringBuffer.append(TEXT_16);
    stringBuffer.append(TEXT_17);
    return stringBuffer.toString();
  }
}
