package ccmtools.generator.java.templates;

import java.util.Iterator;
import ccmtools.generator.java.metamodel.*;

public class CcmComponentContextImplementationTemplate
{
  protected static String nl;
  public static synchronized CcmComponentContextImplementationTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    CcmComponentContextImplementationTemplate result = new CcmComponentContextImplementationTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * DO NOT EDIT!" + NL + " */" + NL + "" + NL + "package ";
  protected final String TEXT_3 = ";" + NL + "                 " + NL + "public class ";
  protected final String TEXT_4 = "_ContextImpl " + NL + "    implements ";
  protected final String TEXT_5 = "_Context" + NL + "{" + NL + "    private ";
  protected final String TEXT_6 = " component;" + NL + "    " + NL + "    public ";
  protected final String TEXT_7 = "_ContextImpl(";
  protected final String TEXT_8 = " component)" + NL + "    {" + NL + "        this.component = component;" + NL + "    }" + NL + "    " + NL + "    /** Receptacle access methods */" + NL + "    " + NL + "    " + NL + "    " + NL + "    " + NL + "    /** CCMContext methods */" + NL + "\t    " + NL + "    public ccm.local.Components.HomeExecutorBase get_CCM_home()" + NL + "    {" + NL + "        throw new RuntimeException(\"Not implemented!\");" + NL + "    }" + NL + "" + NL + "" + NL + "    /** SessionContext methods */" + NL + "    " + NL + "    public Object get_CCM_object()" + NL + "        throws ccm.local.Components.IllegalState" + NL + "    {" + NL + "        throw new RuntimeException(\"Not implemented!\");" + NL + "    }" + NL + "}";

  public String generate(Object argument)
  {
    StringBuffer stringBuffer = new StringBuffer();
     ComponentDef component = (ComponentDef) argument; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append(component.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(component.getJavaNamespace());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(component.getCcmIdentifier());
    stringBuffer.append(TEXT_4);
    stringBuffer.append(component.getAbsoluteJavaCcmName());
    stringBuffer.append(TEXT_5);
    stringBuffer.append(component.getIdentifier());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(component.getCcmIdentifier());
    stringBuffer.append(TEXT_7);
    stringBuffer.append(component.getIdentifier());
    stringBuffer.append(TEXT_8);
    return stringBuffer.toString();
  }
}
