package ccmtools.generator.java.templates;

import ccmtools.generator.java.metamodel.*;

public class CcmHomeImplicitDeclarationTemplate
{
  protected static String nl;
  public static synchronized CcmHomeImplicitDeclarationTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    CcmHomeImplicitDeclarationTemplate result = new CcmHomeImplicitDeclarationTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * DO NOT EDIT!" + NL + " */" + NL + "" + NL + "package ";
  protected final String TEXT_3 = ";" + NL + "                 " + NL + "public interface ";
  protected final String TEXT_4 = "Implicit " + NL + "{" + NL + "    ccm.local.Components.EnterpriseComponent create()" + NL + "        throws ccm.local.Components.CCMException;" + NL + "}";

  public String generate(Object argument)
  {
    StringBuffer stringBuffer = new StringBuffer();
     HomeDef home = (HomeDef) argument; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append(home.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(home.getJavaNamespace());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(home.getCcmIdentifier());
    stringBuffer.append(TEXT_4);
    return stringBuffer.toString();
  }
}
