package ccmtools.generator.java.templates;

import java.util.Iterator;
import ccmtools.generator.java.metamodel.*;

public class ComponentDefApplicationInterfaceTemplate
{
  protected static String nl;
  public static synchronized ComponentDefApplicationInterfaceTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    ComponentDefApplicationInterfaceTemplate result = new ComponentDefApplicationInterfaceTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * DO NOT EDIT!" + NL + " */" + NL + "" + NL + "package ";
  protected final String TEXT_3 = ";" + NL + "                 " + NL + "public interface ";
  protected final String TEXT_4 = " " + NL + "    extends ccm.local.Components.SessionComponent" + NL + "{";
  protected final String TEXT_5 = NL;
  protected final String TEXT_6 = "    " + NL + "}";

  public String generate(Object argument)
  {
    StringBuffer stringBuffer = new StringBuffer();
     ComponentDef component = (ComponentDef) argument; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append(component.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(component.generateJavaNamespace());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(component.generateCcmIdentifier());
    stringBuffer.append(TEXT_4);
    
for(Iterator i = component.getFacet().iterator(); i.hasNext();)
{
    ProvidesDef provides = (ProvidesDef)i.next();

    stringBuffer.append(TEXT_5);
    stringBuffer.append(provides.generateCcmProvidesEquivalentMethodDeclaration());
    
}

    stringBuffer.append(TEXT_6);
    return stringBuffer.toString();
  }
}
