package ccmtools.generator.java.templates;

import ccmtools.generator.java.metamodel.*;

public class HomeDefImplicitApplicationInterfaceTemplate
{
  protected static String nl;
  public static synchronized HomeDefImplicitApplicationInterfaceTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    HomeDefImplicitApplicationInterfaceTemplate result = new HomeDefImplicitApplicationInterfaceTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * DO NOT EDIT!" + NL + " */" + NL + "" + NL + "package ";
  protected final String TEXT_3 = ";" + NL + "                 " + NL + "public interface ";
  protected final String TEXT_4 = "Implicit " + NL + "{" + NL + "    Components.ccm.local.EnterpriseComponent create()" + NL + "        throws Components.ccm.local.CCMException;" + NL + "}";
  protected final String TEXT_5 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
     HomeDef home = (HomeDef) argument; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append(home.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(home.generateJavaNamespace());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(home.generateCcmIdentifier());
    stringBuffer.append(TEXT_4);
    stringBuffer.append(TEXT_5);
    return stringBuffer.toString();
  }
}
