
/***
 * This file was automatically generated by CCM Tools version 0.5.3-pre3
 * <http://ccmtools.sourceforge.net/>
 *
 * Test component business logic implementation.
 * 
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 ***/

#include <cassert>
#include <iostream>
#include <WX/Utils/debug.h>

#include "Test_impl.h"
#include "Test_inBasicType_impl.h"
#include "Test_inUserType_impl.h"

namespace world {
namespace europe {
namespace austria {
namespace ccm {
namespace local {
namespace component {
namespace Test {

using namespace std;
using namespace WX::Utils;

//==============================================================================
// CCM_Test - component implementation
//==============================================================================

CCM_Test_impl::CCM_Test_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

CCM_Test_impl::~CCM_Test_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

const short
CCM_Test_impl::short_value() const
    throw(::ccm::local::Components::CCMException)
{
    return short_value_;
}

void
CCM_Test_impl::short_value(const short value)
  throw(::ccm::local::Components::CCMException)
{
    short_value_ = value;
}

const long
CCM_Test_impl::long_value() const
    throw(::ccm::local::Components::CCMException)
{
    return long_value_;
}

void
CCM_Test_impl::long_value(const long value)
  throw(::ccm::local::Components::CCMException)
{
    long_value_ = value;
}

const unsigned short
CCM_Test_impl::ushort_value() const
    throw(::ccm::local::Components::CCMException)
{
    return ushort_value_;
}

void
CCM_Test_impl::ushort_value(const unsigned short value)
  throw(::ccm::local::Components::CCMException)
{
    ushort_value_ = value;
}

const unsigned long
CCM_Test_impl::ulong_value() const
    throw(::ccm::local::Components::CCMException)
{
    return ulong_value_;
}

void
CCM_Test_impl::ulong_value(const unsigned long value)
  throw(::ccm::local::Components::CCMException)
{
    ulong_value_ = value;
}

const float
CCM_Test_impl::float_value() const
    throw(::ccm::local::Components::CCMException)
{
    return float_value_;
}

void
CCM_Test_impl::float_value(const float value)
  throw(::ccm::local::Components::CCMException)
{
    float_value_ = value;
}

const double
CCM_Test_impl::double_value() const
    throw(::ccm::local::Components::CCMException)
{
    return double_value_;
}

void
CCM_Test_impl::double_value(const double value)
  throw(::ccm::local::Components::CCMException)
{
    double_value_ = value;
}

const char
CCM_Test_impl::char_value() const
    throw(::ccm::local::Components::CCMException)
{
    return char_value_;
}

void
CCM_Test_impl::char_value(const char value)
  throw(::ccm::local::Components::CCMException)
{
    char_value_ = value;
}

const std::string
CCM_Test_impl::string_value() const
    throw(::ccm::local::Components::CCMException)
{
    return string_value_;
}

void
CCM_Test_impl::string_value(const std::string value)
  throw(::ccm::local::Components::CCMException)
{
    string_value_ = value;
}

const bool
CCM_Test_impl::boolean_value() const
    throw(::ccm::local::Components::CCMException)
{
    return boolean_value_;
}

void
CCM_Test_impl::boolean_value(const bool value)
  throw(::ccm::local::Components::CCMException)
{
    boolean_value_ = value;
}

const unsigned char
CCM_Test_impl::octet_value() const
    throw(::ccm::local::Components::CCMException)
{
    return octet_value_;
}

void
CCM_Test_impl::octet_value(const unsigned char value)
  throw(::ccm::local::Components::CCMException)
{
    octet_value_ = value;
}

const world::europe::austria::ccm::local::Color
CCM_Test_impl::color_value() const
    throw(::ccm::local::Components::CCMException)
{
    return color_value_;
}

void
CCM_Test_impl::color_value(const world::europe::austria::ccm::local::Color value)
  throw(::ccm::local::Components::CCMException)
{
    color_value_ = value;
}

const world::europe::austria::ccm::local::Person
CCM_Test_impl::person_value() const
    throw(::ccm::local::Components::CCMException)
{
    return person_value_;
}

void
CCM_Test_impl::person_value(const world::europe::austria::ccm::local::Person value)
  throw(::ccm::local::Components::CCMException)
{
    person_value_ = value;
}

const world::europe::austria::ccm::local::Address
CCM_Test_impl::address_value() const
    throw(::ccm::local::Components::CCMException)
{
    return address_value_;
}

void
CCM_Test_impl::address_value(const world::europe::austria::ccm::local::Address value)
  throw(::ccm::local::Components::CCMException)
{
    address_value_ = value;
}

const world::europe::austria::ccm::local::LongList
CCM_Test_impl::longList_value() const
    throw(::ccm::local::Components::CCMException)
{
    return longList_value_;
}

void
CCM_Test_impl::longList_value(const world::europe::austria::ccm::local::LongList value)
  throw(::ccm::local::Components::CCMException)
{
    longList_value_ = value;
}

const world::europe::austria::ccm::local::StringList
CCM_Test_impl::stringList_value() const
    throw(::ccm::local::Components::CCMException)
{
    return stringList_value_;
}

void
CCM_Test_impl::stringList_value(const world::europe::austria::ccm::local::StringList value)
  throw(::ccm::local::Components::CCMException)
{
    stringList_value_ = value;
}

const world::europe::austria::ccm::local::PersonList
CCM_Test_impl::personList_value() const
    throw(::ccm::local::Components::CCMException)
{
    return personList_value_;
}

void
CCM_Test_impl::personList_value(const world::europe::austria::ccm::local::PersonList value)
  throw(::ccm::local::Components::CCMException)
{
    personList_value_ = value;
}

const world::europe::austria::ccm::local::time_t
CCM_Test_impl::time_t_value() const
    throw(::ccm::local::Components::CCMException)
{
    return time_t_value_;
}

void
CCM_Test_impl::time_t_value(const world::europe::austria::ccm::local::time_t value)
  throw(::ccm::local::Components::CCMException)
{
    time_t_value_ = value;
}

void
CCM_Test_impl::set_session_context(
    ::ccm::local::Components::SessionContext* context)
    throw(::ccm::local::Components::CCMException)
{
    ctx = dynamic_cast<CCM_Test_Context*>(context);
}

void
CCM_Test_impl::ccm_activate()
    throw(::ccm::local::Components::CCMException)
{
   cout << "==== Begin Test Case ====================================" << endl;

    // ---------------------------------------------------------------------
    // Receptacle Attribute Test Cases
    // ---------------------------------------------------------------------

    {
      cout << "Receptacle Attributes (Basic Types) Test...";
      SmartPtr<CCM_BasicTypeInterface> outBasicType =
        ctx->get_connection_outBasicType();

      {
        short value = -7;
        short result;
        outBasicType->short_value(value);
        result = outBasicType->short_value();
        assert(value == result);
      }

      {
        long value = -7777;
        long result;
        outBasicType->long_value(value);
        result = outBasicType->long_value();
        assert(result == value);
      }

      {
        unsigned short value = 7;
        unsigned short result;
        outBasicType->ushort_value(value);
        result = outBasicType->ushort_value();
        assert(result == value);
      }

      {
        unsigned long value = 7777;
        unsigned long result;
        outBasicType->ulong_value(value);
        result = outBasicType->ulong_value();
        assert(result == value);
      }

      {
        float value = -77.77;
        float result;
        outBasicType->float_value(value);
        result = outBasicType->float_value();
        assert(result == value);
      }

      {
        double value = -77.7777;
        double result;
        outBasicType->double_value(value);
        result = outBasicType->double_value();
        assert(result == value);
      }

      {
        char value = 'x';
        char result;
        outBasicType->char_value(value);
        result = outBasicType->char_value();
        assert(result == value);
      }

      {
        string value = "0123456789";
        string result;
        outBasicType->string_value(value);
        result = outBasicType->string_value();
        assert(value == result);
      }

      {
        bool value = true;
        bool result;
        outBasicType->boolean_value(value);
        result = outBasicType->boolean_value();
        assert(result == value);
      }

      {
        unsigned char value = 0xff;
        unsigned char result;
        outBasicType->octet_value(value);
        result = outBasicType->octet_value();
        assert(result == value);
      }
      cout << "OK!" << endl;
    }

    {
      cout << "Receptacle Attributes (User Types) Test...";
      SmartPtr<CCM_UserTypeInterface> outUserType =
        ctx->get_connection_outUserType();
      {
        // enum Color {red, green, blue, black, orange}
        Color value = blue;
        Color result;
        outUserType->color_value(value);        
        result = outUserType->color_value();

        assert(result == value);
      }

      {
        // struct Person { long id; string name; }
        Person value;
        Person result;
        value.name = "Egon";   
        value.id = 3;
        outUserType->person_value(value);
        result = outUserType->person_value();

        assert(result.name == value.name);
        assert(result.id == value.id);
      }

      {
        // struct Address { string street; long number; Person resident; }
        Address value;
        Address result;
        Person person;
        value.street = "Waltendorf";   
        value.number = 7;
        person.name = "Egon";   
        person.id   = 3;
        value.resident = person;
        outUserType->address_value(value);
        result = outUserType->address_value();

        assert(result.street == value.street);
        assert(result.number == value.number);
        assert(result.resident.name == value.resident.name);
        assert(result.resident.id == value.resident.id);
      }

      {
        // typedef sequence<long> LongList
        const int MAX_SIZE = 100; 
        LongList value;
        LongList result;

        value.reserve(MAX_SIZE);
        for(int i=0;i<MAX_SIZE;i++) {
          value.push_back(i);
        }
        outUserType->longList_value(value);
        result = outUserType->longList_value();

        assert((int)result.size() == MAX_SIZE);
        for(int i=0; i < (int)result.size(); i++) {
          assert(result[i] == value[i]);
        }
      }

      {
        // typedef sequence<string> StringList
        const int MAX_SIZE = 100; 
        StringList value;
        StringList result;
        for(int i=0; i < MAX_SIZE; i++) {
          string s = "Egon";
          value.push_back(s);
        }
        outUserType->stringList_value(value);
        result = outUserType->stringList_value();

        assert((int)result.size() == MAX_SIZE);
        for(int i=0; i < (int)result.size(); i++) {
          assert(result[i] == value[i]);
        }
      }

      {
        // typedef sequence<Person> PersonList
        const int MAX_SIZE = 100; 
        PersonList value;
        PersonList result;
        for(int i=0; i < MAX_SIZE; i++) {
          Person p;
          p.name = "Andrea";
          p.id   = i;
          value.push_back(p);
        }

        outUserType->personList_value(value);
        result = outUserType->personList_value();

        assert((int)result.size() == MAX_SIZE);
        for(int i=0; i < (int)result.size(); i++) {
          assert(result[i].name == value[i].name);
          assert(result[i].id == value[i].id);
        }
      }

      {
        // typedef long time_t;
        time_t value = -7777;
        time_t result;
        outUserType->time_t_value(value);
        result = outUserType->time_t_value();
        assert(result == value);
      }

      cout << "OK!" << endl;
    }

   cout << "==== End Test Case =====================================" << endl;
}

void
CCM_Test_impl::ccm_passivate()
    throw(::ccm::local::Components::CCMException)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

void
CCM_Test_impl::ccm_remove()
    throw(::ccm::local::Components::CCMException)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

//==============================================================================
// world::europe::austria::ccm::local::CCM_BasicTypeInterface facet implementation
//==============================================================================

world::europe::austria::ccm::local::CCM_BasicTypeInterface*
CCM_Test_impl::get_inBasicType()
{
    inBasicType_impl* facet = new inBasicType_impl(this);
    return dynamic_cast< world::europe::austria::ccm::local::CCM_BasicTypeInterface*>(facet);
}

//==============================================================================
// world::europe::austria::ccm::local::CCM_UserTypeInterface facet implementation
//==============================================================================

world::europe::austria::ccm::local::CCM_UserTypeInterface*
CCM_Test_impl::get_inUserType()
{
    inUserType_impl* facet = new inUserType_impl(this);
    return dynamic_cast< world::europe::austria::ccm::local::CCM_UserTypeInterface*>(facet);
}

} // /namespace Test
} // /namespace component
} // /namespace local
} // /namespace ccm
} // /namespace austria
} // /namespace europe
} // /namespace world

