/**
 * Test case: home exception
 *
 */

exception can_not_create {};

component Test
{
  attribute string id;
};

home TestHome manages Test
{
  factory create_with_exception(in string id)
    raises (can_not_create);
};

