/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;
           
import Components.AlreadyConnected;
import Components.CCMObject;
import Components.CCMException;
import Components.Cookie;             
import Components.ExceededConnectionLimit;
import Components.InvalidConnection;
import Components.NoConnection;

  
                 
public interface C1 
    extends CCMObject
{
    /** Attribute equivalent methods */

    String a1()
        throws CCMException;     

    void a1(String value)
        throws CCMException;     


    int a2()
        throws CCMException;     

    void a2(int value)
        throws CCMException;     
    

    /** Facet equivalent methods */
    
    wamas.Test.I1 provide_i1();
    
    
    /** Receptacle equivalent methods */

    void connect_i2(wamas.Test.I2 localObj)
        throws AlreadyConnected, InvalidConnection;

    wamas.Test.I2 disconnect_i2()
        throws NoConnection;
        
    wamas.Test.I2 get_connection_i2();
    
}
