/**
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_I1Impl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package wamas.Test; 

import Components.CCMException;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class C1i1Impl 
    implements CCM_I1
{
    /** Reference to the facet's component implementation */
    private C1Impl component;

    public C1i1Impl(C1Impl component)
    {
        this.component = component;
    }
 


    /** Business logic implementations */

   
    
     

}
