/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;

import Components.CCMException;     
import Components.SessionComponent;

              
              
public interface CCM_C2 
    extends SessionComponent
{
    /** Component attribute accessor methods */
    

    int b()
        throws CCMException;     

    void b(int value)
        throws CCMException;     
    


    /** Facet implementation factory methods */

    wamas.Test.CCM_I2 get_i2();
    
}
