/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * 
 * H2 Implementation
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE!
 *
 * @author
 * @version
 */

package wamas.Test;

import Components.CCMException;           
import Components.EnterpriseComponent;


      
/**
 * This class implements a component home's attributes and factory methods.  
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class H2Impl 
    implements CCM_H2
{
    public H2Impl()
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }
    
    public EnterpriseComponent create()
        throws CCMException
    {
        return (EnterpriseComponent) new C2Impl();
    }
}
