
#ifndef __HOME__system_ServerHome__
#define __HOME__system_ServerHome__

#include <system/Server.idl>

module system {

home ServerHome manages system::Server
 
 
{

};

}; // /module system

#endif
