#ifndef __COMPONENT__system_Server__
#define __COMPONENT__system_Server__

#include <system/Login.idl>

module system {

component Server
 
 
{

  provides system::Login login;

};

}; // /module system

#include <system/ServerHome.idl>

#endif
