/**
 * This file was automatically generated by CCM Tools 
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_UserTypeInterfaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world;

import java.util.List;

import Components.*;


/**
 * This class implements a component facet's methods.
 *  // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */
public class SuperTestuserTypeImpl implements CCM_UserTypeInterface
{
    /** Reference to the facet's component implementation */
    private world.SuperTestImpl component;

    public SuperTestuserTypeImpl(world.SuperTestImpl component)
    {
        this.component = component;
    }

    /** Business logic implementations */

    public Color f1(Color p1, Holder<Color> p2, Holder<Color> p3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f1(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public Person f2(Person p1, Holder<Person> p2, Holder<Person> p3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f2(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public Address f3(Address p1, Holder<Address> p2,
            Holder<Address> p3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f3(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public List<Integer> f4(List<Integer> p1, Holder<List<Integer>> p2,
            Holder<List<Integer>> p3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f4(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public List<String> f5(List<String> p1, Holder<List<String>> p2,
            Holder<java.util.List<String>> p3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f5(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public List<Person> f6(List<Person> p1, Holder<List<Person>> p2, Holder<List<Person>> p3)
        throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f6(p1, p2, p3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    public int f7(int t1, Holder<Integer> t2, Holder<Integer> t3) throws CCMException
    {
        try
        {
            return component.ctx.get_connection_innerUserType().f7(t1, t2, t3);
        }
        catch (java.lang.Exception e)
        {
            e.printStackTrace();
            throw new CCMException(e.getMessage(), CCMExceptionReason.SYSTEM_ERROR);
        }
    }
}
