/**
 * test case: module mixed
 *
 */

#include "Console.idl"

module world {

component Test
{
  attribute string prompt;

  provides europe::Console console;
};

home TestHome manages Test
{
};

}; // end of module world
