#ifndef __MODULE_REOPENED__IDL__
#define __MODULE_REOPENED__IDL__

module world
{
	typedef long LongType;
	// typedef long longType; !!!

	enum Color
	{
    		red,
    		green,
    		blue,
		black,
		orange
	};

	struct Person
	{
    		long id;
    		string name;
	};
}; // end of module world

module america
{
  typedef long LongArray[10];
  
  typedef sequence<long> LongSeq;
		
}; // end of module america


module world
{
	module europe
	{
		struct Address
		{
			string street;
    			long number;
    			Person resident;
		};

		interface InterfaceBasicTypeAttributes
		{
		        attribute float floatValue;
			attribute double doubleValue;
			attribute long double lDoubleValue;
		};
	}; // end of module europe


	module europe
	{
		module austria
		{
			interface InterfaceUserType
			{
				::LongType typedefOpAbsolute(in ::LongType p1);										
			        LongType typedefOpRelative(in LongType p1);		
				
				::world::Color enumOpAbsolute(in ::world::Color p1);

				Color enumOpRelative(in Color p1);
								
				::world::europe::Address structOpAbsolute(in ::world::europe::Address p1);

				Address structOpRelative(in Address p1);
				
				::america::LongArray arrayOpAbsolute(in ::america::LongArray p1);
				
				::america::LongSeq sequenceOpAbsolute(in ::america::LongSeq p1); 
				
				::world::europe::InterfaceBasicTypeAttributes 
					interfaceOpAbsolute(in ::world::europe::InterfaceBasicTypeAttributes p1);				
				InterfaceBasicTypeAttributes interfaceOpRelative(in InterfaceBasicTypeAttributes p1);
			};
			
		}; // end of module austria
	}; // end of module europe
}; // end of module world	

#endif // __MODULE_NESTED__IDL__

