/**
 * include test
 *
 * We define the interfaces for facet, receptacles and component 
 * in separated files.  
 * The include statement is used to bring the files together.
 */

#include "Console.idl"

module WORLD {

component Hello
{
  attribute string prompt;

  provides Console console;
};

home HelloHome manages Hello
{
};

}; // end of module WORLD
