/******************************************************************************/
/*  Project: VP1.0 local                                                      */
/*  File:    RecordConsumer.idl                                               */
/*  Version: 0.1                                                              */
/*  Date:    Dezember 2002                                                    */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Author : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/*                                                                            */
/*  Change1:                                                                  */
/******************************************************************************/

#include "Record.idl"

struct Consumed
{
  boolean error;
  long accepted;
  long acknowledged;
};

interface RecordConsumer
{
  Consumed consume(in RecordList rl);
  Consumed flush();
};

