all: 
	if test "`uname`" = "Interix"; then \
		idl `unixpath2win ${CCMTOOLS_HOME}/idl/ccmtools/corba/Components/ccmtools.idl`; \
	else \
		idl ${CCMTOOLS_HOME}/idl/ccmtools/corba/Components/ccmtools.idl; \
	fi
	