/**
 * module test
 */

module world {
  module europe {
    module austria {

      component Test
      {
	attribute string prompt;
      };
      
      home TestHome manages Test
      {
      };
      
    }; // end of module austria
  }; // end of module europe
}; // end of module world
