#ifndef __ARRAY_TEST__IDL__
#define __ARRAY_TEST__IDL__

typedef long LongArray[10];
typedef long LongMatrix[10][11];
typedef long LongCube[10][11][12];

typedef string StringArray[10];
typedef string StringMatrix[10][11];
typedef string StringCube[10][11][12];

typedef wstring WStringArray[10];
typedef wstring WStringMatrix[10][11];
typedef wstring WStringCube[10][11][12];

#endif // __ARRAY_TEST__IDL__
