/**
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_C1 component business logic.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */

package wamas.Test;
   
import Components.CCMException;     
import Components.SessionContext; 

  
   
/**
 * This class implements component equivalent and supported interfaces
 * as well as component attributes.
 * Additionally, session component callback methods must be implemented.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */   
public class C1Impl 
    implements CCM_C1
{
    /** Supported interface attribute variables */
    
    

    /** Component attribute variables */
    
    private String a1_;
    private int a2_; 

    public CCM_C1_Context ctx;
    
    
    public C1Impl()
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }


    /* 
     * Supported interface methods 
     */

    /** Supported interface attributes */
    
    
    
    /** Supported interface methods */
        


    /** Component attribute accessor methods */


    public String a1()
        throws CCMException
    {
        return this.a1_;
    }     

    public void a1(String value)
        throws CCMException
    {
        this.a1_ = value;
    }


    public int a2()
        throws CCMException
    {
        return this.a2_;
    }     

    public void a2(int value)
        throws CCMException
    {
        this.a2_ = value;
    }
    


    /** Facet implementation factory methods */
    

    public wamas.Test.CCM_I1 get_i1()
    {
        return new wamas.Test.C1i1Impl(this);
    }
    

    /** Component callback methods */
    
    public void set_session_context(SessionContext ctx) 
        throws CCMException
    {
        this.ctx = (CCM_C1_Context)ctx; 
    }

    public void ccm_activate() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_passivate() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_remove() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }
}
