
/**
 * This file was automatically generated by CCM Tools
 * <http://ccmtools.sourceforge.net/>
 *
 * application::Login facet class implementation. 
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 **/

#include <cassert>
#include <iostream>

#include "Server_login_impl.h"


namespace application {

using namespace std;

Server_login_impl::Server_login_impl(application::Server_impl* component_impl)
  : component(component_impl)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

Server_login_impl::~Server_login_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

bool
Server_login_impl::isValidUser(const application::PersonData& person)
throw(Components::CCMException, application::InvalidPersonData)
{
  if(person.name.length() == 0)
    throw application::InvalidPersonData();

  if(person.id == 277 
     && person.name == "eteinik"
     && person.group == USER) {
    return true;
  }
  else {
    return false;
  }
}

} // /namespace application
