/******************************************************************************/
/*  Project: VP1.0 local                                                      */
/*  File   : Handler.idl                                                      */
/*  Version: 0.1                                                              */
/*  Date   : Dezember 2002                                                    */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon Teiniker                                                    */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

#include "RecordConsumer.idl"

component Handler
{
  provides RecordConsumer recConsumer;
};

home HandlerHome manages Handler
{
};
