/******************************************************************************/
/*  Project: VP1.0 local                                                      */
/*  File   : LbaClient.idl                                                    */
/*  Version: 0.1                                                              */
/*  Date   : Dezember 2002                                                    */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon Teiniker                                                    */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

#include "Gui.idl"

interface LbaClientOp
{
  void write(in LbaRecord r);
  LbaRecordSet read(in LbaRecord r);
};


component LbaClient supports LbaClientOp
{
  uses Gui gui;
};


home LbaClientHome manages LbaClient
{
};



