/******************************************************************************/
/*  Project: VP1.0 local                                                      */
/*  File   : LbaSession.idl                                                   */
/*  Version: 0.1                                                              */
/*  Date   : Dezember 2002                                                    */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon Teiniker                                                    */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

#include "Gui.idl"
#include "RecordConsumer.idl"

component LbaSession 
{
  provides Gui gui;
  uses RecordConsumer recConsumer;
};

home LbaSessionHome manages LbaSession
{
};
