// $Id$

typedef sequence<double> DoubleSeq;
typedef sequence<DoubleSeq> DoubleSeqSeq;
typedef double DoubleArray[10];

component MyReal
{
  attribute DoubleSeq seq1;
  attribute DoubleSeqSeq seq2;
  attribute DoubleArray array1;
  attribute double value1;
};

home MyRealHome manages MyReal
{
};
