#include "ifaces/auth.idl"
#include "ifaces/udbbrowser.idl"

module owil {
module udb {
      
component UserDB_DBSQL {
   provides UserPassAuthentication auth;
   provides UserDBBrowser browser;

   attribute boolean update_stat;
};

home UserDB_DBSQL_Home manages UserDB_DBSQL {};

}; // end of module udb
}; // end of module owil
