#ifndef __INTERFACE_BASIC_TYPE_OPERATION__IDL__
#define __INTERFACE_BASIC_TYPE_OPERATION__IDL__

interface InterfaceBasicTypeOperation 
{
  short         shortOp(in short p1, inout short p2, out short p3);
  long          longOp(in long p1, inout long p2, out long p3);
  long long	lLongOp(in long long p1, inout long long p2, out long long p3);
  unsigned short uShortOp(in unsigned short p1, inout unsigned short p2, out unsigned short p3);
  unsigned long uLongOp(in unsigned long p1, inout unsigned long p2, out unsigned long p3);
  unsigned long long uLLongOp(in unsigned long long p1, inout unsigned long long p2, out unsigned long long p3);

  float         floatOp(in float p1, inout float p2, out float p3);
  double        doubleOp(in double p1, inout double p2, out double p3);
  long double	lDoubleOp(in long double p1, inout long double p2, out long double p3);
	
  char          charOp(in char p1, inout char p2, out char p3);
  wchar         wcharOp(in wchar p1, inout wchar p2, out wchar p3);
  string        stringOp(in string p1, inout string p2, out string p3);
  string<5>     bStringOp(in string<5> p1, inout string<5> p2, out string<5> p3);
  wstring       wstringOp(in wstring p1, inout wstring p2, out wstring p3);
  wstring<5>    bWstringOp(in wstring<5> p1, inout wstring<5> p2, out wstring<5> p3);
  
  boolean       booleanOp(in boolean p1, inout boolean p2, out boolean p3);
  octet         octetOp(in octet p1, inout octet p2, out octet p3);
  any          	anyOp(in any p1, inout any p2, out any p3);
  Object        objectOp(in Object p1, inout Object p2, out Object p3);
};

#endif // __INTERFACE_BASIC_TYPE_OPERATION__IDL__
