#ifndef __INTERFACE_INHERITANCE__IDL__
#define __INTERFACE_INHERITANCE__IDL__

#include "EmptyInterface.idl"

interface InterfaceSuperTypeOne 
{
	attribute long attr1;
    	long op1(in string str);
};

interface InterfaceSuperTypeTwo
{
	attribute long attr2;
    long op2(in string str);
};

interface InterfaceSubType 
	: InterfaceSuperTypeOne, InterfaceSuperTypeTwo, EmptyInterface 
{
	// attribute long attr1; // Redefinition !!!!
	attribute long attr3;
    	long op3(in string str);
};

#endif // __INTERFACE_INHERITANCE__IDL__
