#include "logindatalist.idl"
#include "exc.idl"

#ifndef __OWUDB__LDBBROWSER_IDL__
#define __OWUDB__LDBBROWSER_IDL__

module owil {
module udb {

interface LoginDBBrowser {
   LoginDataList get_logins_of_user(in string user)
   raises(NoSuchUser,
          DatabaseError);

   LoginDataList get_all_logins()
   raises(DatabaseError);
};

};
};

#endif

