#ifndef __OWUDB__LOGINDATA_IDL__
#define __OWUDB__LOGINDATA_IDL__

module owil {
module udb {

struct LoginData {
   string system;
   string login;
   long attr;
   string beschreib;
   string grp;
   string prok;
   string persnr;
};

};
};

#endif

