#ifndef __OWUDB__PERSDATA_IDL__
#define __OWUDB__PERSDATA_IDL__

module owil {
module udb {

struct PersData {
   string persnr;
   string name;
   long tage;
   string passwd;
   string lang;
   long flags;
   long autologout;
   long maxmenu;
   long /*time_t*/ letztlogin;
   long /*time_t*/ errlogin;
   long /*time_t*/ pwdablauf;
};

};
};

#endif

