// $Id$
/**
 * Test case: receptacle user types 
 *
 */

typedef long time_t;

enum Color {red, green, blue, black, orange};

struct Value {
  string s;
  double d;
};

typedef sequence<Value> map;

typedef double doubleArray[10];

interface Console {
  time_t foo1(in time_t p1, inout time_t p2, out time_t p3);
  Color  foo2(in Color p1, inout Color p2, out Color p3);
  Value  foo3(in Value p1, inout Value p2, out Value p3);
  map  foo4(in map p1, inout map p2, out map p3);
  doubleArray foo5(in doubleArray p1, inout doubleArray p2, out doubleArray p3);
};

component Hello
{
  uses Console console;
};

home HelloHome manages Hello
{
};

