#ifndef __SEQUENCE_TEST__IDL__
#define __SEQUENCE_TEST__IDL__

#include "../enum/DayOfWeek.idl"
#include "../struct/TimeOfDay.idl"
#include "../typedef/TypedefTest.idl"
#include "../array/ArrayTest.idl"

typedef sequence<long> LongSeq;
typedef sequence<long, 10> LongBoundedSeq;

typedef sequence<string> StringSeq;
typedef sequence<string, 11> StringBoundedSeq;

typedef sequence<wstring> WStringSeq;
typedef sequence<wstring, 12> WStringBoundedSeq;



typedef sequence<DayOfWeek> EnumSeq;
typedef sequence<DayOfWeek, 13> EnumBoundSeq;

typedef sequence<TimeOfDay> StructSeq;
typedef sequence<TimeOfDay, 14> StructBoundSeq;


//typedef sequence<LongType> LongTypeSequence; !!!

//typedef sequence<LongArray> LongArraySeq; !!!

//typedef sequence<LongSeq> MetaLongSeq; !!!


#endif // __SEQUENCE_TEST__IDL__
