/*  $Id$
*/

#include<mico/CCM.idl>

typedef sequence<long> IntegerVector;


/**
 * A stack for integers.
 */
interface IntegerStack
{
    attribute IntegerVector field;
    attribute long maxSize;
    boolean isEmpty();
    boolean isFull();
    void push( in long value );
    long pop();
    long top();
};


component Math
{
    provides IntegerStack stack;
};

home MathHome manages Math
{
};

local interface CCM_Math_Session : CCM_Math,
   Components::SessionComponent
{
};
