/**
 * Test case: receptacle multiple
 *
 */

module world
{

  interface IFace 
  {
    long println(in string str);
  };
  
  component Test
  {
    uses multiple IFace port;
  };
  
  home TestHome manages Test
  {
  };
  
}; // /module world
