#ifndef __NAMES__IDL__
#define __NAMES__IDL__

/*
	typedef long LongType;
	// Within a naming scope, identifiers must be consistently capitalized !
	typedef long longType; // should be an Error!!!
*/

/*
	// A name in a nested scope cannot be the same as a name in its
	// immediatela enclosing scope!
	module world
	{
		module world // should be an Error!!!
		{
			typedef string StringType;
			
		}; // end of module world
	}; // end of module world
*/

	// An interface cannot define a name that is the same as the name of the interface:
	interface Name
	{
		typedef string Name; // should be an Error!!! 
	};

#endif // __NAMES__IDL__

