
#ifndef __world_europe_TEST__
#define __world_europe_TEST__

#include "IFace.idl"

module world
{
  module europe
  {
    component Test
    {
      provides world::IFace iface;
    };

    home TestHome manages Test
    {
    };

  }; // /module europe

}; // /module world

#endif
