/**
 * This file was automatically generated by CCM Tools version 0.6.6
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_Test component business logic.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */

package world.ccm.local;
   
import ccm.local.Components.SessionContext; 

import america.ccm.local.CCM_SubType;
import america.ccm.local.SubType;
import ccm.local.Components.CCMException;
  
   
/**
 * This class implements component equivalent and supported interfaces
 * as well as component attributes.
 * Additionally, session component callback methods must be implemented.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */   
public class TestImpl 
    implements CCM_Test
{
    /** Supported interface attribute variables */

    private int attr1_;
    private int attr2_;
    private int attr3_;    
    

    /** Component attribute variables */
     

    public CCM_Test_Context ctx;
    
    
    public TestImpl()
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }


    /* 
     * Supported interface methods 
     */

    /** Supported interface attributes */


    public int attr1()
        throws CCMException
    {
        return this.attr1_;
    }     

    public void attr1(int value)
        throws CCMException
    {
        this.attr1_ = value;
    }


    public int attr2()
        throws CCMException
    {
        return this.attr2_;
    }     

    public void attr2(int value)
        throws CCMException
    {
        this.attr2_ = value;
    }


    public int attr3()
        throws CCMException
    {
        return this.attr3_;
    }     

    public void attr3(int value)
        throws CCMException
    {
        this.attr3_ = value;
    }
    
    
    
    /** Supported interface methods */
    
    public int op1(String str)
        throws CCMException
    {
       System.out.println("app> " + str);
        return str.length();
    }    

    public int op2(String str)
        throws CCMException
    {
        System.out.println("app> " + str);
        return str.length();
    }    

    public int op3(String str)
        throws CCMException
    {
        System.out.println("app> " + str);
        return str.length();
    }    
    


    /** Component attribute accessor methods */
    


    /** Facet implementation factory methods */
        

    /** Component callback methods */
    
    public void set_session_context(SessionContext ctx) 
        throws CCMException
    {
        this.ctx = (CCM_Test_Context)ctx; 
    }

    public void ccm_activate() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_passivate() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_remove() 
        throws CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }
}
