/*
 * This file was automatically generated by CCM Tools 
 * <http://ccmtools.sourceforge.net/>
 *
 * CCM_VoidTypeInterface facet class definition.
 */

#ifndef __FACET__world_europe_austria_ccm_local_inVoidType__H__
#define __FACET__world_europe_austria_ccm_local_inVoidType__H__

#include <world/europe/austria/VoidTypeInterface.h>

#include "Test_impl.h"

namespace world {
namespace europe {
namespace austria {

class Test_inVoidType_impl
    : virtual public CCM_VoidTypeInterface
{
  protected:
    Test_impl* component;
    // This attribute is accessed by explicite set and get methods
    // which are part of VoidTypeInterface.
    long attr;
    
  public:
    Test_inVoidType_impl(Test_impl* component_impl);
    virtual ~Test_inVoidType_impl();

    virtual 
    void 
    f1(const long p1) 
    throw(::Components::ccm::local::CCMException);

    virtual 
    long 
    f2() 
    throw(::Components::ccm::local::CCMException);

};

} // /namespace austria
} // /namespace europe
} // /namespace world

#endif // __FACET__world_europe_austria_ccm_local_inVoidType__H__

