DOCUMENT_NAME=tutorial
PARTS=\
  titlepage.tex \
  Introduction/Introduction.tex \
  Introduction/CBSE.tex \
  Introduction/ComponentDefinition.tex \
  Introduction/CCMOverview.tex\
  Introduction/CCMToolsOverview.tex \
  Introduction/LCAC.tex \
  ComponentDevelopment/ComponentDevelopment.tex \
  ComponentDevelopment/HelloComponent.tex \
  ComponentDevelopment/ComponentStructure.tex \
  ComponentDevelopment/TestDrivenDevelopment.tex \
  ComponentDevelopment/ComponentDebugging.tex \
  ComponentDevelopment/UMLComponentDesign.tex \
  SystemDevelopment/SystemDevelopment.tex \
  SystemDevelopment/NestedComponentComposition.tex \
  SystemDeployment/SystemDeployment.tex \
  SystemDeployment/RemoteComponent.tex \
  Appendix/ManPage.tex \
  Appendix/CcmtoolsInstallation.tex \
  Appendix/ConfixInstallation.tex \
  Appendix/MicoInstallation.tex 

FIGURES= \
  figures/Environment.fig \
  figures/CCMSymbol.fig \
  figures/CCMArchitecture.fig \
  figures/CcmToolsOverview.fig \
  figures/ContainerComponentlogicBusinesslogic.fig \
  figures/Adapter1.fig \
  figures/Assembly.fig \
  figures/AssemblyGraph.fig \
  figures/AssemblyGraph2.fig \
  figures/CcmToolsArchitecture.fig \
  figures/Component.fig \
  figures/ComponentGeneratorTools.fig \
  figures/ComponentLogicBusinessLogic.fig \
  figures/ConnectComponents.fig \
  figures/Container.fig \
  figures/DesignerTask.fig \
  figures/DeveloperTask.fig \
  figures/DevelopmentProcess.fig \
  figures/LCAC_Overview.fig \
  figures/LCAC_ProcessModel.fig \
  figures/RemoteAssembly.fig \
  figures/TestDrivenDevelopment.fig \
  figures/TestArchitecture.fig \
  figures/TestClientSequenceDiagram.fig \
  figures/UMLComponentDesign.fig \
  figures/LocalAdapterConcept.fig \
  figures/RemoteComponentCall.fig \
  figures/NestedAssembly.fig \
  figures/NestedToFlatAssembly.fig \
  figures/SuperComponentCreate.fig \
  figures/SuperComponentConfigurationComplete.fig \
  figures/SuperComponentRemove.fig \
  figures/ProcessComponentDevelopment.fig


ALL_SOURCES=$(DOCUMENT_NAME).tex $(PARTS) $(FIGURES)

HTML_OUTPUT_DIR=$(DOCUMENT_NAME)-html
HTML_STAMP=$(HTML_OUTPUT_DIR).stamp
EPS_FIGURES=$(subst .fig,.eps,$(FIGURES))

all: ps pdf html

ps: $(DOCUMENT_NAME).ps

pdf: $(DOCUMENT_NAME).pdf

html: $(HTML_STAMP)

dvi: $(DOCUMENT_NAME).dvi

bi: $(DOCUMENT_NAME).tex
	bibtex $(DOCUMENT_NAME)
	latex $(DOCUMENT_NAME).tex
	latex $(DOCUMENT_NAME).tex
$(DOCUMENT_NAME).dvi: $(ALL_SOURCES) $(EPS_FIGURES)
	latex $(DOCUMENT_NAME).tex
clean::
	rm -f *.aux *.log *.toc *.bbl *.blg *.lof *.lot $(DOCUMENT_NAME).dvi

$(DOCUMENT_NAME).pdf: $(DOCUMENT_NAME).dvi
	dvipdf -sPAPERSIZE=a4 $(DOCUMENT_NAME)
clean::
	rm -f $(DOCUMENT_NAME).pdf

$(DOCUMENT_NAME).ps: $(DOCUMENT_NAME).dvi
	dvips -f $< > $@
clean::
	rm -f $(DOCUMENT_NAME).ps

eps: $(EPS_FIGURES)
$(EPS_FIGURES): %.eps: %.fig
	fig2dev -L eps $< $@
clean::
	rm -f $(EPS_FIGURES)

$(HTML_STAMP): $(ALL_SOURCES)
	rm -rf $(HTML_OUTPUT_DIR)
	latex2html -mkdir -nofootnode -dir $(HTML_OUTPUT_DIR) $(DOCUMENT_NAME).tex
	touch $@
clean::
	rm -f $(HTML_STAMP)
	rm -rf $(HTML_OUTPUT_DIR)



