module wamas {


    module Test {

        interface I1 {
            string value();
			void run(in long x);
        };

        interface I2 {
            /* empty */
        };

        interface I3 {
            /* empty */
        };

        component C1 {
            attribute string a1;
            attribute long a2;
            provides I1 i1;
            uses I2 i2;
        };

        home H1 manages C1 {
        };

        component C2 {
            attribute long b;
            provides I2 i2;
            uses I3 i3;
        };

        home H2 manages C2 {
        };

    };  // /module Test


    component C3
    {
        attribute long b;
        provides Test::I1 i1;
        uses Test::I3 i3;
    };

    home H3 manages C3 {
    };


};  // /module wamas
