

module application
{
  enum Group
  {
    GUEST,
    USER,
    ADMIN
  };

  struct PersonData
  {
    long id;
    string name;
    string password;
    Group group;
  };

  exception InvalidPersonData
  {
    string message;
  };


  interface Login
  {
    boolean isValidUser(in PersonData person)
      raises(InvalidPersonData);
  };


  component Server
  {
    provides Login login; 
  };

  home ServerHome manages Server
  {
  };

};
