/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */
 
package application.ccm.remote;

import ccm.local.CorbaConverterException;

import application.ccm.local.InvalidPersonData;


public class InvalidPersonDataCorbaConverter
{
    /** Convert a local Java type into a CORBA type */
    public static application.InvalidPersonData convert(InvalidPersonData in)
       throws CorbaConverterException
    {
        application.InvalidPersonData out = new application.InvalidPersonData();

        out.message = (in.getMessage());
        return out;
    }


    /** Convert a CORBA type into a local Java type */
    public static InvalidPersonData convert(application.InvalidPersonData in)
       throws CorbaConverterException
    {
        InvalidPersonData out = new InvalidPersonData();
        out.setMessage((in.message));
        return out;
    }
};
