/**
 * Test case: attribute
 *
 */


interface ACommon
{
  void set_attrib_a(in long a);
  long get_attrib_a();
};

component Hello
{
  attribute ACommon the_a;
};

home HelloHome manages Hello
{
};

