
#include <system/Group.idl>

#ifndef __STRUCT__system_PersonData__
#define __STRUCT__system_PersonData__

module system {

struct PersonData
{
  long id;
  string name;
  string password;
  system::Group group;

};

}; // /module system

#endif
