#ifndef __FES_IDL__
#define __FES_IDL__

#include "OFFS.idl"
#include "FET.idl"
#include "HISTORY.idl"
#include "FTSM.idl"

// Feldstamm
/*
typedef struct _FES {
  char fesFeldId[FELDID_LEN+1];
  long fesSpalte;
  long fesEbene;
  OFFS fesOffs;
  FET fesFet;
  long fesModId;
  HISTORY fesHist;
  long fesAbcWert;
  long fesGang;
  long fesFAttrLls;
  FTSM fesFts;
  long fesTePile;
  char fesWamodInfo[WAMODINFO_LEN+1];
  long fesSpalteExt;
  long fesEbeneExt;
  long fesGangExt;
  long fesSpalteExt2;
  long fesEbeneExt2;
  long fesGangExt2;
  long fesRegalExt;
  long fesRegalExt2;
  char fesWamodInfo2[WAMODINFO_LEN+1];
  char fesLBINV_LagIdInv[LAGID_LEN+1];
  char fesLKS_LagKlasse[LAGKLASSE_LEN+1];
  char fesREG_LagIdPhy[LAGID_LEN+1];
  long fesREG_Regalteil;
  long fesREG_Regal;
  char fesLBST_LagIdSt[LAGID_LEN+1];
  char fesLBCL_LagIdCl[LAGIDCL_LEN+1];
  char fesFTS_FetId[FETID_LEN+1];
  char fesLBWA_LagIdWa[LAGIDWA_LEN+1];
  char fesLBWE_LagIdWe[LAGIDWE_LEN+1];
  long fesFAttrWap;
} FES;
*/

struct FES {
  string  fesFeldId;
  long    fesSpalte;
  long    fesEbene;
  OFFS    fesOffs;
  FET     fesFet;
  long    fesModId;
  HISTORY fesHist;
  long    fesAbcWert;
  long    fesGang;
  long    fesFAttrLls;
  FTSM    fesFts;
  long    fesTePile;
  string  fesWamodInfo;
  long    fesSpalteExt;
  long    fesEbeneExt;
  long    fesGangExt;
  long    fesSpalteExt2;
  long    fesEbeneExt2;
  long    fesGangExt2;
  long    fesRegalExt;
  long    fesRegalExt2;
  string  fesWamodInfo2;
  string  fesLBINV_LagIdInv;
  string  fesLKS_LagKlasse;
  string  fesREG_LagIdPhy;
  long    fesREG_Regalteil;
  long    fesREG_Regal;
  string  fesLBST_LagIdSt;
  string  fesLBCL_LagIdCl;
  string  fesFTS_FetId;
  string  fesLBWA_LagIdWa;
  string  fesLBWE_LagIdWe;
  long    fesFAttrWap;
};

#endif
