#ifndef __FET_IDL__
#define __FET_IDL__

#include "VOL.idl"
#include "RAS.idl"

/*
typedef struct _FET 
{
 VOL fetVol;
 RAS fetRas;
 long fetLMax;
 long fetGew;
} FET;
*/

struct FET 
{
  VOL  fetVol;
  RAS  fetRas;
  long fetLMax;
  long fetGew;
};

#endif
