#ifndef __FTSM_IDL__
#define __FTSM_IDL__

#include "KFTS_KOO.idl"

/*
typedef struct _FTSM {
  KFTS_KOO K;
  long FFM;
  long LMFXVR;
  long GFXVR;
  long GEWM;
} FTSM;
*/

struct FTSM {
  KFTS_KOO K;
  long FFM;
  long LMFXVR;
  long GFXVR;
  long GEWM;
};


#endif
