#ifndef __HISTORY_IDL__
#define __HISTORY_IDL__

#include "time.idl"

/*
typedef struct _HISTORY 
{
 char AnUser[USR_LEN+1];
 char AeUser[USR_LEN+1];
 time_t AeZeit;
 time_t AnZeit;
} HISTORY;
*/

struct HISTORY 
{
  string AnUser;
  string AeUser;
  time_t AeZeit;
  time_t AnZeit;
};

#endif
