#ifndef __KFTS_KOO_IDL__
#define __KFTS_KOO_IDL__

#include "KFTS.idl"

/*
typedef struct _KFTS_KOO {
  KFTS kfts_kooX;
  KFTS kfts_kooY;
  KFTS kfts_kooZ;
} KFTS_KOO;
*/

struct KFTS_KOO {
  KFTS kfts_kooX;
  KFTS kfts_kooY;
  KFTS kfts_kooZ;
};

#endif
