#ifndef __DAY_OF_WEEK__IDL__
#define __DAY_OF_WEEK__IDL__

module world
{

	enum DayOfWeek
	{
		Mon, 
		Tue,
		Wed,
		Thu,
		Fri,
		Sat,
		Sun
	};

}; // /module world

#endif // __DAY_OF_WEEK__IDL__
