#! /usr/bin/env python

import os, sys

java = 'JAVA' in os.environ.keys() and os.environ['JAVA'] or 'java'
src = 'ccmtools.UI.ConsoleCodeGenerator'
home = ''
if 'CCMTOOLS_HOME' in os.environ.keys():
    home = '-DCCMTOOLS_HOME="%s"' % os.environ['CCMTOOLS_HOME']

os.execvp(java, [java, src, home] + sys.argv[1:])
