#! /usr/bin/env python

## ccmtools-c++-generate : C++ component generator wrapper
## Leif Johnson <leif@ambient.2y.net>
## Copyright (C) 2003 Salomon Automation
##
##
## This program is free software; you can redistribute it and/or modify it unde
## the terms of the GNU General Public License as published by the Free Softwar
## Foundation; either version 2 of the License, or (at your option) any later
## version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
## details.
##
## You should have received a copy of the GNU General Public License along with
## this program; if not, write to the Free Software Foundation, Inc., 59 Temple
## Place - Suite 330, Boston, MA 02111-1307, USA.

import os, sys, time

ENABLE_DEBUG = 0
ENABLE_PYTHON_TEST = 0
ENABLE_APPLICATION = 0

FILES = ''
INCLUDES = ''
DEFINES = ''

INSTALL_DIR = ''
SOURCE_DIR = ''
CCMTOOLS_PACKAGE = '.'

if 'CCMTOOLS_PACKAGE' in os.environ.keys():
    CCMTOOLS_PACKAGE = os.environ['CCMTOOLS_PACKAGE']

USAGE = '''Usage: ccmtools-c++-generate [OPTION]... IDL-FILE...

Generate C++ components and test components based on the given IDL files.

Options:
    -a, --application           Generate skeletons for business logic
    -d, --debug                 Enable debugging in generated source code
    -DFOO[=BAR]                 Define FOO (as BAR) for generated source code
    -h, --help                  Print out this help
    -i DIR, --install=DIR       Use DIR as the install prefix [Confix default]
    -IDIR                       Add DIR to the include path for IDL files
    -p NAME, --package=NAME     Set package name to NAME [%s]
    -s DIR, --source=DIR        Store generated source code in DIR
                                [./<PACKAGE-NAME>]
    -y, --python                Enable Python testing in generated source code
    -V, --version               Print out ccmtools version information

The environment variable CCMTOOLS_PACKAGE can be used to set the package name.

Generated application logic and user types files will be copied to the current
directory, unless they exist already, or if the -f option is enabled. Make sure
you have a "ccmtools" profile in your $HOME/.confix configuration file.''' \
    % CCMTOOLS_PACKAGE

## handle arguments.

index = 1
while index < len(sys.argv):
    arg = sys.argv[index]
    index += 1

    if arg == '-c': CODE_VERSION = sys.argv[index]; index += 1
    elif arg.startswith('--c') and arg.find('=') > 0:
        CODE_VERSION = arg.split('=')[1]

    elif arg == '-a' or arg.startswith('--a'): ENABLE_APPLICATION = 1
    elif arg == '-d' or arg.startswith('--d'): ENABLE_DEBUG = 1
    elif arg.startswith('-D'): DEFINES += ' ' + arg
    elif arg == '-h' or arg.startswith('--h'): print USAGE; sys.exit(0)
    elif arg == '-i': INSTALL_DIR = sys.argv[index]; index += 1
    elif arg.startswith('--i') and arg.find('=') > 0:
        INSTALL_DIR = arg.split('=')[1]

    elif arg.startswith('-I'): INCLUDES += ' ' + arg
    elif arg == '-p': CCMTOOLS_PACKAGE = sys.argv[index]; index += 1
    elif arg.startswith('--pa') and arg.find('=') > 0:
        CCMTOOLS_PACKAGE = arg.split('=')[1]

    elif arg == '-s': SOURCE_DIR = sys.argv[index]; index += 1
    elif arg.startswith('--s') and arg.find('=') > 0:
        SOURCE_DIR = arg.split('=')[1]

    elif arg == '-y' or arg.startswith('--py'): ENABLE_PYTHON_TEST = 1
    elif arg == '-V' or arg.startswith('--v'):
        os.execlp('ccmtools-generate', 'ccmtools-generate', '--version')

    elif arg.find('.idl') > 0: FILES += ' ' + arg

## check argument values.

if not FILES:
    print 'No input IDL files specified!'
    print
    print USAGE
    sys.exit(1)

if not INCLUDES.strip():
    for file in FILES.split():
        path = '-I' + (os.path.split(file)[0] or os.curdir)
        if INCLUDES.find(path) < 0: INCLUDES += path

if ENABLE_DEBUG:       DEFINES += r' -DCCM_DEBUG'
if ENABLE_PYTHON_TEST: DEFINES += r' -DCCM_TEST_PYTHON'

SOURCE_DIR = SOURCE_DIR or CCMTOOLS_PACKAGE

if (sys.platform[:3] == 'win' and not SOURCE_DIR[1:3] == ':\\') or \
       not SOURCE_DIR.startswith(os.sep):
    SOURCE_DIR = os.path.join(os.getcwd(), SOURCE_DIR)

## generate components. the generation order is (a) idl3mirror, (b) c++local
## tests (c) c++ mirror components, (d) c++ python wrappers, and (e) the real
## c++ components.

cmd = 'ccmtools-generate -o %s %s' % (SOURCE_DIR, DEFINES)
app = ENABLE_APPLICATION and '-a' or ''

if ENABLE_DEBUG:
    idl3_dir = os.path.join(SOURCE_DIR, 'idl3')

    if os.system('ccmtools-generate -o %s %s idl3mirror %s %s' %
                 (idl3_dir, DEFINES, INCLUDES, FILES)):
        print 'Error while generating IDL3 mirror files.'
        sys.exit(1)

    if os.system('%s c++local-test %s %s' % (cmd, INCLUDES, FILES)):
        print 'Error while generating C++ local test files.'
        sys.exit(1)

    cwd = os.getcwd()
    os.chdir(idl3_dir)
    if os.system('%s -I. c++local %s %s *' % (cmd, app, INCLUDES)):
        print 'Error while generating C++ mirror components.'
        os.chdir(cwd)
        sys.exit(1)
    os.chdir(cwd)

if ENABLE_PYTHON_TEST:
    if os.system('%s c++python -e %s %s' % (cmd, INCLUDES, FILES)):
        print 'Error while generating Python bindings.'
        sys.exit(1)

if os.system('%s c++local %s %s %s' % (cmd, app, INCLUDES, FILES)):
    print 'Error generating local C++ components.'
    sys.exit(1)

