#! /usr/bin/env python

import os, sys
import string

java = 'JAVA' in os.environ.keys() and os.environ['JAVA'] or 'java'
src = 'uml2idl.Main'

print ' '.join(['>>', java, src] + sys.argv[1:])
os.execvp(java, [java, src] + sys.argv[1:])
