/**
 * This file was automatically generated by CCM Tools version 0.6.3
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_UserTypeInterfaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world.europe.austria.ccm.local;
                 
import ccm.local.Components.*;
 
/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class Test_mirroruserType_mirrorImpl 
    implements world.europe.austria.ccm.local.CCM_UserTypeInterface
{
    /** Reference to the facet's component implementation */
    private world.europe.austria.ccm.local.Test_mirrorImpl component;

    public Test_mirroruserType_mirrorImpl(world.europe.austria.ccm.local.Test_mirrorImpl component)
    {
        System.out.println("+Test_mirroruserType_mirrorImpl.userType_mirrorImpl()");
        this.component = component;
    }

    private world.europe.austria.Color color_value_;
    private world.europe.austria.Person person_value_;
    private world.europe.austria.Address address_value_;
    private int[] longList_value_;
    private String[] stringList_value_;
    private world.europe.austria.Person[] personList_value_;
    private int time_t_value_; 


    /** Business logic implementations */

  

    public world.europe.austria.Color color_value()
        throws ccm.local.Components.CCMException
    {
        return this.color_value_;
    }     

    public void color_value(world.europe.austria.Color value)
        throws ccm.local.Components.CCMException
    {
        this.color_value_ = value;
    }


    public world.europe.austria.Person person_value()
        throws ccm.local.Components.CCMException
    {
        return this.person_value_;
    }     

    public void person_value(world.europe.austria.Person value)
        throws ccm.local.Components.CCMException
    {
        this.person_value_ = value;
    }


    public world.europe.austria.Address address_value()
        throws ccm.local.Components.CCMException
    {
        return this.address_value_;
    }     

    public void address_value(world.europe.austria.Address value)
        throws ccm.local.Components.CCMException
    {
        this.address_value_ = value;
    }


    public int[] longList_value()
        throws ccm.local.Components.CCMException
    {
        return this.longList_value_;
    }     

    public void longList_value(int[] value)
        throws ccm.local.Components.CCMException
    {
        this.longList_value_ = value;
    }


    public String[] stringList_value()
        throws ccm.local.Components.CCMException
    {
        return this.stringList_value_;
    }     

    public void stringList_value(String[] value)
        throws ccm.local.Components.CCMException
    {
        this.stringList_value_ = value;
    }


    public world.europe.austria.Person[] personList_value()
        throws ccm.local.Components.CCMException
    {
        return this.personList_value_;
    }     

    public void personList_value(world.europe.austria.Person[] value)
        throws ccm.local.Components.CCMException
    {
        this.personList_value_ = value;
    }


    public int time_t_value()
        throws ccm.local.Components.CCMException
    {
        return this.time_t_value_;
    }     

    public void time_t_value(int value)
        throws ccm.local.Components.CCMException
    {
        this.time_t_value_ = value;
    }
 
    
     

}