#ifndef __SIMPLE_TYPEDEF__IDL__
#define __SIMPLE_TYPEDEF__IDL__

typedef short ShortType;

module world
{
  typedef short ShortType; // OK: new scope for ShortType
};

typedef short Shorttype; // Error: re-definition of ShortType

#endif  //__SIMPLE_TYPEDEF__IDL__


