#ifndef __USER_TYPE_STRUCT__IDL__
#define __USER_TYPE_STRUCT__IDL__

#include "../DayOfWeek.idl"
#include "../europe/TimeOfDay.idl"

module world
{
	module america
	{	
		struct UserTypeStruct
		{
			DayOfWeek enumMember;
			world::europe::TimeOfDay structMember;
		};
		
	}; // /module america
}; // /module world

#endif // __USER_TYPE_STRUCT__IDL__
