#ifndef __COMPONENT_USER_TYPE_ATTRIBUTE__IDL__
#define __COMPONENT_USER_TYPE_ATTRIBUTE__IDL__

#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>
#include <struct/Address.idl>
#include <array/BasicTypeArray.idl>
#include <sequence/BasicTypeSequence.idl>
#include <interface/InterfaceBasicTypeAttributes.idl>

component ComponentUserTypeAttribute
{
	attribute LongType typedefValue;
	attribute Color enumValue;
	attribute Address structValue;
	attribute LongArray arrayValue;
	attribute LongSeq sequenceValue;
  	attribute InterfaceBasicTypeAttributes interfaceValue;
};

#endif // __COMPONENT_USER_TYPE_ATTRIBUTE__IDL__
