#ifndef __COMPONENT_ATTRIBUTE_EXCEPTIONS__IDL__
#define __COMPONENT_ATTRIBUTE_EXCEPTIONS__IDL__

#include<exception/ExceptionEmpty.idl>
#include<exception/ExceptionBasicType.idl>
#include<exception/ExceptionUserType.idl>
#include<struct/Person.idl>

component ComponentAttributeExceptions
{
    attribute long longValue
	getRaises(ExceptionEmpty)
        setRaises(ExceptionBasicType, ExceptionUserType);

    attribute Person structValue
        getRaises(ExceptionEmpty)
        setRaises(ExceptionBasicType);
};

#endif // __COMPONENT_ATTRIBUTE_EXCEPTIONS__IDL__
