#ifndef __COMPONENT_FACET_AND_RECEPTACLE_IDL__
#define __COMPONENT_FACET_AND_RECEPTACLE_IDL__

#include <interface/InterfaceBasicTypeAttributes.idl>
#include <interface/InterfaceUserTypeOperation.idl>

component ComponentFacet
{
	provides InterfaceBasicTypeAttributes basicTypes;
	provides InterfaceUserTypeOperation userTypes;
};

home ComponentFacetHome
	manages ComponentFacet
{
};


/**
 * Here we use the same names for receptacles as we have
 * used in the other component for receptacles.
 */

component ComponentReceptacle
{
  uses InterfaceBasicTypeAttributes basicTypes; 
  uses InterfaceUserTypeOperation userTypes; 
};

home ComponentReceptacleHome
	manages ComponentReceptacle
{
};

#endif // __COMPONENT_FACET_AND_RECEPTACLE__IDL__
