#ifndef __HOME_FACTORY_EXCEPTION__IDL__
#define __HOME_FACTORY_EXCEPTION__IDL__

#include<exception/ExceptionEmpty.idl>
#include<exception/ExceptionBasicType.idl>
#include<exception/ExceptionUserType.idl>


component HomeFactoryException
{
	attribute string Id;
};

home HomeFactoryExceptionHome
	manages HomeFactoryException
{
    factory createWithExceptions()
         raises(ExceptionEmpty, ExceptionBasicType, ExceptionUserType);
};

#endif // __HOME_FACTORY_EXCEPTION__IDL__
