#ifndef __HOME_ATTRIBUTE_EXCEPTIONS__IDL__
#define __HOME_ATTRIBUTE_EXCEPTIONS__IDL__

#include <component/ComponentSimple.idl> 

#include<exception/ExceptionEmpty.idl>
#include<exception/ExceptionBasicType.idl>
#include<exception/ExceptionUserType.idl>
#include<struct/Person.idl>

home HomeAttributeExceptions
    manages ComponentSimple
{
    attribute long longValue
        getraises(ExceptionEmpty)
        setraises(ExceptionBasicType, ExceptionUserType);

    attribute Person structValue
        getraises(ExceptionEmpty)
        setraises(ExceptionBasicType);
};

#endif // __HOME_ATTRIBUTE_EXCEPTIONS__IDL__
