#ifndef __HOME_TYPES__IDL__
#define __HOME_TYPES__IDL__


component HomeTypes
{

};

home HomeTypesHome
	manages HomeTypes
{

  typedef long LongType;

  enum Color
  {
    red,
    green,
    blue,
    black,
    orange
  };

  struct Person
  {
    long id;
    string name;
  };	

  typedef long LongArray[10];
  
  typedef sequence<long> LongSeq;
  
  
  void foo(in LongType p1, 
	   in Color p2, 
	   in Person p3, 
	   in LongArray p4, 
	   in LongSeq p5);
  
};

#endif // __HOME_TYPES__IDL__
