#ifndef __HOME_SUPPORTED_INTERFACE__IDL__
#define __HOME_SUPPORTED_INTERFACE__IDL__

#include <interface/InterfaceBasicTypeAttributes.idl>
#include <interface/InterfaceUserTypeOperation.idl>

component HomeSupportedInterface
{
    attribute string Id;
};

home HomeSupportedInterfaceHome
    supports InterfaceBasicTypeAttributes, InterfaceUserTypeOperation
    manages HomeSupportedInterface
{
};

#endif // __HOME_SUPPORTED_INTERFACE__IDL__
