
/**
 * This file was automatically generated by CCM Tools version 0.5.4
 * <http://ccmtools.sourceforge.net/>
 *
 * ccm::local::CCM_SubType facet class implementation. 
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 **/

#include <cassert>
#include <iostream>
#include <wx/utils/debug.h>

#include "Test_iface_impl.h"

using namespace std;
using namespace wx::utils;

namespace ccm {
namespace local {

Test_iface_impl::Test_iface_impl(ccm::local::Test_impl* component_impl)
  : component(component_impl)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

Test_iface_impl::~Test_iface_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

const long
Test_iface_impl::attr3() const
    throw(::Components::ccm::local::CCMException)
{
    return attr3_;
}

void
Test_iface_impl::attr3(const long value)
    throw(::Components::ccm::local::CCMException)
{
    attr3_ = value;
}

const long
Test_iface_impl::attr2() const
    throw(::Components::ccm::local::CCMException)
{
    return attr2_;
}

void
Test_iface_impl::attr2(const long value)
    throw(::Components::ccm::local::CCMException)
{
    attr2_ = value;
}

const long
Test_iface_impl::attr1() const
    throw(::Components::ccm::local::CCMException)
{
    return attr1_;
}

void
Test_iface_impl::attr1(const long value)
    throw(::Components::ccm::local::CCMException)
{
    attr1_ = value;
}

long
Test_iface_impl::op3(const std::string& str)
throw(::Components::ccm::local::CCMException)
{
    cout << str << endl;
    return str.length();
}

long
Test_iface_impl::op2(const std::string& str)
throw(::Components::ccm::local::CCMException)
{
    cout << str << endl;
    return str.length();
}

long
Test_iface_impl::op1(const std::string& str)
throw(::Components::ccm::local::CCMException)
{
    cout << str << endl;
    return str.length();
}

} // /namespace local
} // /namespace ccm
