/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas;
   
import java.util.logging.Logger;

import Components.Assembly;
import Components.AssemblyFactory;
import Components.CCMException;
import Components.CCMObject;
import Components.CreateFailure;
import Components.RemoveFailure;

import ccmtools.local.ServiceLocator;

public class H3Adapter 
    implements H3
{
    private Logger logger = ServiceLocator.instance().getLogger();
    
    private CCM_H3 localInterface;
    private AssemblyFactory assemblyFactory;
    
    protected H3Adapter()
    {
        this(null, null);
    }
    
    public H3Adapter(CCM_H3 localInterface)
    {
        this(localInterface, null);
    }
    
    public H3Adapter(CCM_H3 localInterface, 
            AssemblyFactory assemblyFactory)
    {
        logger.fine("localInterface = " + localInterface + ", " + assemblyFactory);
        this.localInterface = localInterface;
        this.assemblyFactory = assemblyFactory;
    }

    
    public C3 create()
        throws CreateFailure
    {
        logger.fine("");
        try
        {
            CCM_C3 c = (CCM_C3)localInterface.create();
            C3 component;
            if(assemblyFactory != null)
            {
                Assembly assembly = assemblyFactory.create();
                component = new C3Adapter(c, assembly);
                assembly.build(component);
            }
            else
            {
                component = new C3Adapter(c);
            }
            return component;
        }
        catch(CCMException e)
        {
            throw new CreateFailure();
        }    
    }
    
    public void remove_component(CCMObject component) 
        throws CCMException, RemoveFailure
    {
        logger.fine("");	
        component.remove();
    }

    public CCMObject create_component() 
        throws CCMException, CreateFailure
    {
        logger.fine("");
        return create();
    }
}
