/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;
            
import Components.HomeExecutorBase;
import Components.IllegalState;       
import Components.NoConnection;
            
import java.util.logging.Logger;
import ccmtools.local.ServiceLocator;
                     
public class CCM_C2_ContextImpl 
    implements wamas.Test.CCM_C2_Context
{
    private Logger logger = ServiceLocator.instance().getLogger();

    private C2 component;
    
    public CCM_C2_ContextImpl(C2 component)
    {
        logger.fine("component = " + component);
        this.component = component;
    }
    
    /** Receptacle access methods */

    public wamas.Test.I3 get_connection_i3()
        throws NoConnection
    {
        logger.fine("");
        return component.get_connection_i3();
    }
      
    
    
    /** CCMContext methods */
	    
    public HomeExecutorBase get_CCM_home()
    {
        logger.fine("");
        throw new RuntimeException("Not implemented!");
    }


    /** SessionContext methods */
    
    public Object get_CCM_object()
        throws IllegalState
    {
        logger.fine("");
        throw new RuntimeException("Not implemented!");
    }
}
