/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;
                 
public interface H1 
    extends H1Explicit, H1Implicit
{
}
