/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;

import Components.CCMHome;              

public interface H2Explicit 
    extends CCMHome
{
}
