/*
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package wamas.Test;
                 
import java.util.logging.Logger;

import Components.CCMException;  
import ccmtools.local.ServiceLocator;

                  
                  
public class I2Adapter 
    implements I2
{
    private Logger logger = ServiceLocator.instance().getLogger();
    
    private CCM_I2 localInterface;
    
    protected I2Adapter()
    {
        logger.fine("");
    }

    public I2Adapter(CCM_I2 localInterface)
    {
        logger.fine("localInterface = " + localInterface);
        this.localInterface = localInterface;
    }
            
        
    
}
