/**
 * This file was automatically generated by CCM Tools version 0.6.3
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_IFaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world.ccm.local;
                 
import ccm.local.Components.*;
 
/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class Test_mirrorport_mirrorImpl 
    implements world.ccm.local.CCM_IFace
{
    /** Reference to the facet's component implementation */
    private world.ccm.local.Test_mirrorImpl component;

    public Test_mirrorport_mirrorImpl(world.ccm.local.Test_mirrorImpl component)
    {
        System.out.println("+Test_mirrorport_mirrorImpl.port_mirrorImpl()");
        this.component = component;
    }
 


    /** Business logic implementations */

    public int println(String str)
        throws ccm.local.Components.CCMException
    {
        System.out.println("  println()");
	
	System.out.println("> " + str);
    	return str.length();
    }    

}
