
module world 
{

  interface IFace
  {
    long foo(in string str);
  };

  component Test
  {
	provides IFace inPort;
	
	uses IFace singlePort;
	
	uses multiple IFace multiPort;
  };

  home TestHome manages Test
  {
  };

}; // /module world
