/***
 * Tutorial: HelloWorld Example
 *
 *
 **/

module world
{ 
  interface Hello 
  { 
      string sayHello(); 
  }; 

  component Server 
  { 
      provides Hello hello;
  }; 

  home ServerHome manages Server
  {
  };
};
