
module world 
{

  interface IFace
  {
    long foo(in string str);
  };

  component Test
  {
    provides IFace inPort;

    uses IFace	   outPort;
	uses multiple IFace outPorts;
  };

  home TestHome manages Test
  {
  };

}; // /module world
