/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package application.ccm.local;

import java.util.logging.Logger;

import Components.ccm.local.CCMHome;
import Components.ccm.local.CCMException;
import Components.ccm.local.AssemblyFactory;

import ccm.local.HomeFinder;
import ccm.local.ServiceLocator;


public class ServerHomeDeployment 
{
    /** Default logger instance */
    private static Logger logger = ServiceLocator.instance().getLogger();
    
    
    public static CCMHome create()
        throws CCMException
    {
        logger.fine("");
        return new ServerHomeAdapter((CCM_ServerHome)ServerHomeFactory.create());    
    }

    public static CCMHome create(AssemblyFactory factory)
        throws CCMException
    {
        logger.fine("assemblyFactory = " + factory);    
        return new ServerHomeAdapter((CCM_ServerHome)ServerHomeFactory.create(), factory);    
    }


    public static void deploy(String name)
        throws CCMException
    {
        logger.fine("name = " + name);
        HomeFinder.instance().register_home(create(), name);    
    }
    
    public static void deploy(String name, AssemblyFactory factory)
        throws CCMException
    {
        logger.fine("name = " + name + ", assemblyFactory = " + factory);
        HomeFinder.instance().register_home(create(factory), name);    
    }
    
    
    public static void undeploy(String name)
    {
        logger.fine("name = " + name);
        HomeFinder.instance().unregister_home(name);    
    }
}
