#ifndef __BASIC_TYPE_STRUCT__IDL__
#define __BASIC_TYPE_STRUCT__IDL__


struct BasicTypeStruct
{
	short 			shortMember;	
	long 			longMember;
	long long               llongMember;
	unsigned short 	        ushortMember;
	unsigned long 	        ulongMember;
	unsigned long long      ullongMember; 
	
	float 			floatMember;
	double 			doubleMember;
	long double             ldoubleMember;
	
	char 			charMember;
	wchar     		wcharMember;
	string 			stringMember;
	string<10>		stringBoundedMember;
	wstring			wstringMember;
	wstring<11>		wstringBoundedMember;	
		
	boolean 		booleanMember;
	octet 			octetMember;	
	any 			anyMember;
	Object			objectMember;
	
	fixed<9,2>      fixedMember;
};

#endif // __BASIC_TYPE_STRUCT__IDL__
