#ifndef __USER_TYPE_STRUCT__IDL__
#define __USER_TYPE_STRUCT__IDL__

#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>

#include "Person.idl"

struct UserTypeStruct
{
	MetaLongType	 typedefMember;
	Color enumMember;
	Person structMember;
	//...
};


#endif // __USER_TYPE_STRUCT__IDL__
