/**
 * This file was automatically generated by CCM Tools version 0.9.0
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_OutputStreamImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package wamas.system; 

import Components.CCMException;
import wamas.io.CCM_OutputStream;
import wamas.io.OutputStream;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class ConsolestderrImpl 
    implements CCM_OutputStream
{
    /** Reference to the facet's component implementation */
    private ConsoleImpl component;

    public ConsolestderrImpl(ConsoleImpl component)
    {
        this.component = component;
    }
 


    /** Business logic implementations */

   
    
     

    public void write(char c)
        throws CCMException
    {
    	System.err.print(c);
    	
    }    

}
