/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package system.ccm.local;

import Components.ccm.local.CCMException;     
import Components.ccm.local.SessionComponent;

              
              
public interface CCM_Server 
    extends SessionComponent
{
    /** Component attribute accessor methods */
        


    /** Facet implementation factory methods */

    system.ccm.local.CCM_Login get_login();
    
}