/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package system.ccm.local;
                 
import Components.ccm.local.NoConnection;             

public interface CCM_Server_Context 
    extends Components.ccm.local.SessionContext
{
    /** Receptacle access methods */     
}