/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package system.ccm.local;

import Components.ccm.local.CCMException;             
 
 
/** 
 * Java interface declaration (based on the corresponding IDL interface).
 */
public interface Login 
    
{


    boolean login (PersonData person)     
        throws CCMException,
            InvalidData;    


}