/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package system.ccm.local;

import Components.ccm.local.CCMHome;              

public interface ServerHomeExplicit 
    extends CCMHome
{
}