package application;


/**
* application/_ServerHomeExplicitStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_ServerHome.idl
* Wednesday, August 16, 2006 12:57:50 PM CEST
*/

public class _ServerHomeExplicitStub extends org.omg.CORBA.portable.ObjectImpl implements application.ServerHomeExplicit
{


  /**
    		 * This operation causes the component denoted by the reference to exit.
    		 */
  public void remove_component (Components.CCMObject comp) throws Components.RemoveFailure
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("remove_component", true);
                Components.CCMObjectHelper.write ($out, comp);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Components/RemoveFailure:1.0"))
                    throw Components.RemoveFailureHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                remove_component (comp        );
            } finally {
                _releaseReply ($in);
            }
  } // remove_component

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:application/ServerHomeExplicit:1.0", 
    "IDL:Components/CCMHome:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ServerHomeExplicitStub
