package application;


/**
* application/Login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_Login.idl
* Wednesday, August 16, 2006 12:57:47 PM CEST
*/

public interface Login extends LoginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Login
