package application;


/**
* application/ServerHomeExplicitOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_ServerHome.idl
* Wednesday, August 16, 2006 12:57:50 PM CEST
*/

public interface ServerHomeExplicitOperations  extends Components.CCMHomeOperations
{
} // interface ServerHomeExplicitOperations
