package application;


/**
* application/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_Server.idl
* Wednesday, August 16, 2006 12:57:49 PM CEST
*/

public interface Server extends ServerOperations, Components.CCMObject, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
