/******************************************************************************/
/*  Project: localPrototype  (C++)                                            */
/*  File   : Calculator.idl                                                   */
/*  Version: 0.4                                                              */
/*  Date   : October 2002                                                     */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/


interface EuroCalculator
{
  double eur_to_ats(in double eur);
  double ats_to_eur(in double ats);
};
