/******************************************************************************/
/*  Project: localPrototype  (C++)                                            */
/*  File   : IntegerFacet.idl                                                 */
/*  Version: 0.4                                                              */
/*  Date   : October 2002                                                     */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

interface IntegerFacet
{
  long add(in long a, in long b);
  long sub(in long a, in long b);
};
