/******************************************************************************/
/*  Project: localPrototype  (C++)                                            */
/*  File   : ShowFacet.idl                                                    */
/*  Version: 0.4                                                              */
/*  Date   : October 2002                                                     */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

interface ShowFacet
{
  void print_string(in string msg);
};
