#ifndef __CONSTANT_EXPRESSION__IDL__
#define __CONSTANT_EXPRESSION__IDL__

/**
 * Arithmetic Operations
 */
 
const long LONG_ADD_CONST = 7 + 3;
const long LONG_SUB_CONST = 3 - 7 ;
const long LONG_MUL_CONST = 7 * 3;
const long LONG_DIV_CONST = 7 / 3;
const long LONG_MOD_CONST = 7 % 3;

const long LONG_RESULT = (LONG_ADD_CONST + LONG_SUB_CONST) * LONG_MUL_CONST / LONG_DIV_CONST;


const double DOUBLE_ADD_CONST = 7.71 + 3.32;
const double DOUBLE_SUB_CONST = 7.71 - 3.32;
const double DOUBLE_MUL_CONST = 7.71 * 3.32;
const double DOUBLE_DIV_CONST = 7.71 / 3.32;

const double DOUBLE_RESULT = (DOUBLE_ADD_CONST + DOUBLE_SUB_CONST) * DOUBLE_MUL_CONST / DOUBLE_DIV_CONST;

#endif // __CONSTANT_EXPRESSION__IDL__
