#ifndef __GLOBAL_CONSTANTS__IDL__
#define __GLOBAL_CONSTANTS__IDL__

const short SHORT_CONST = -3;
const long LONG_CONST = -7777;
const long long LONG_LONG_CONST = 7777777;
const unsigned short USHORT_CONST = 7;
const unsigned long ULONG_CONST = 7777;

const float FLOAT_CONST = 3.14;
const double DOUBLE_CONST = 3.1415926;

const char CHAR_CONST = 'c';
//const wchar WCHAR_CONST = L'c';

const string STRING_CONST = "1234567890";  
const wstring WSTRING_CONST = L"1234567890";

const boolean BOOLEAN_CONST = TRUE;
const octet OCTET_CONST = 255;

//const fixed FIXED_CONST = 3.14D; !!!


/**
 * Arithmetic Operations
 */
 
const long LONG_ADD_CONST = 7 + 3;
const long LONG_SUB_CONST = 3 - 7 ;
const long LONG_MUL_CONST = 7 * 3;
const long LONG_DIV_CONST = 7 / 3;
const long LONG_MOD_CONST = 7 % 3;

const long LONG_RESULT = (LONG_ADD_CONST + LONG_SUB_CONST) * LONG_MUL_CONST / LONG_DIV_CONST;

const double DOUBLE_ADD_CONST = 7.71 + 3.32;
const double DOUBLE_SUB_CONST = 7.71 - 3.32;
const double DOUBLE_MUL_CONST = 7.71 * 3.32;
const double DOUBLE_DIV_CONST = 7.71 / 3.32;

const double DOUBLE_RESULT = (DOUBLE_ADD_CONST + DOUBLE_SUB_CONST) * DOUBLE_MUL_CONST / DOUBLE_DIV_CONST;

#endif // __GLOBAL_CONSTANTS__IDL__
