#ifndef __EXCEPTION_USER_TYPE__IDL__
#define __EXCEPTION_USER_TYPE__IDL__

#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>
#include <struct/Address.idl>
#include <array/BasicTypeArray.idl>
#include <sequence/BasicTypeSequence.idl>

exception ExceptionUserType
{
	LongType 	typedefMember;
	Color		enumMember;
	Address		structMember;
	LongArray	arrayMember;
	LongSeq		sequencemember;
};

#endif // __EXCEPTION_USER_TYPE__IDL__
