/**
 * Test case: 
 *
 */

interface Constants
{
  const boolean BOOLEAN_CONST = TRUE;
  const octet OCTET_CONST = 255;
  const short SHORT_CONST = -10;
  const unsigned short USHORT_CONST = 7;
  const long LONG_CONST = -7777;
  const unsigned long ULONG_CONST = 7777;
  const char CHAR_CONST = 'c';
  const string STRING_CONST = "1234567890";  
  const float FLOAT_CONST = 3.14;
  const double DOUBLE_CONST = 3.1415926;

  boolean getBooleanValue();
  octet getOctetValue();

  short getShortValue();
  unsigned short getUnsignedShortValue();
  
  long getLongValue();
  unsigned long getUnsignedLongValue();
  
  char getCharValue();
  string getStringValue();
  
  float getFloatValue();
  double getDoubleValue();
};


component Test
{
  provides Constants iface;
};

home TestHome manages Test
{
};


