/***
 * CCM Tools Test Client
 *
 * This file was automatically generated by .
 *         <http://ccmtools.sourceforge.net/>
 *
 * This test client is part of the mirror component test concept. For each
 * component a corresponding mirror component will be instantiated.
 * All component ports will be connected to the mirror component's ports.
 * Additionally, developers can add some testing code to validate supported
 * interfaces as well as component attribute access.
 ***/

#include <cassert>
#include <iostream>

#include <Components/ccmtools.h>

#include <SuperTestHomeMirror_entry.h>
#include <SuperTestHome_entry.h>
#include <BasicTestHome_entry.h>
#include <UserTestHome_entry.h>

#include <SuperTestHomeMirror_gen.h>
#include <SuperTestHome_gen.h>
#include <BasicTestHome_gen.h>
#include <UserTestHome_gen.h>

#include <assembly.h>

using namespace std;

int main(int argc, char *argv[])
{
    cout << ">>>> Start Test Client: " << __FILE__ << endl;

    SuperTest::SmartPtr mySuperTest;
    SuperTestMirror::SmartPtr mySuperTestMirror;
    Components::Object::SmartPtr SuperTest_provides_basicType;
    Components::Object::SmartPtr SuperTest_provides_userType;

    Components::Cookie SuperTest_ck_basicType;
    Components::Cookie SuperTest_ck_userType;

    Components::Object::SmartPtr SuperTest_uses_innerBasicType;
    Components::Object::SmartPtr SuperTest_uses_innerUserType;

    Components::Cookie SuperTest_ck_innerBasicType;
    Components::Cookie SuperTest_ck_innerUserType;

    int error = 0;


    error  += deploy_BasicTestHome("BasicTestHome");
    error  += deploy_UserTestHome("UserTestHome");

    Components::AssemblyFactory::SmartPtr assembly_factory(
    		new Components::AssemblyFactoryTemplate<Assembly>());

    error += deploy_with_assembly_SuperTestHome("SuperTestHome", assembly_factory);

    error += deploy_SuperTestHomeMirror("SuperTestHomeMirror");
    if(error)
    {
        cerr << "BOOTSTRAP ERROR: Can't deploy component homes!" << endl;
        return(error);
    }

    try
    {
    		Components::HomeFinder* homeFinder = Components::HomeFinder::Instance();
        SuperTestHome::SmartPtr
        		mySuperTestHome(dynamic_cast<SuperTestHome*>(
                homeFinder->find_home_by_name("SuperTestHome").ptr()));

        SuperTestHomeMirror::SmartPtr
        		mySuperTestHomeMirror(dynamic_cast<SuperTestHomeMirror*>(
                homeFinder->find_home_by_name("SuperTestHomeMirror").ptr()));

        mySuperTest = mySuperTestHome->create();
        mySuperTestMirror = mySuperTestHomeMirror->create();

        SuperTest_provides_basicType = mySuperTest->provide_facet("basicType");
        SuperTest_provides_userType = mySuperTest->provide_facet("userType");

		mySuperTestMirror->connect("basicType", SuperTest_provides_basicType);
        mySuperTestMirror->connect("userType", SuperTest_provides_userType);

        mySuperTest->configuration_complete();
        mySuperTestMirror->configuration_complete();


      	mySuperTestMirror->disconnect("basicType", SuperTest_ck_basicType);
      	mySuperTestMirror->disconnect("userType", SuperTest_ck_userType);

      	mySuperTest->remove();
      	mySuperTestMirror->remove();
    }
    catch (Components::HomeNotFound& e)
    {
        cout << "DEPLOYMENT ERROR: can't find a home!" << endl;
        return -1;
    }
    catch (Components::NotImplemented& e)
    {
        cout << "DEPLOYMENT ERROR: function not implemented: "
	     << e.what() << endl;
        return -1;
    }
    catch (Components::InvalidName& e)
    {
        cout << "DEPLOYMENT ERROR: invalid name during connection: "
             << e.what() << endl;
        return -1;
    }
    catch (...)
    {
        cout << "DEPLOYMENT ERROR: there is something wrong!" << endl;
        return -1;
    }

    error =  undeploy_BasicTestHome("BasicTestHome");
    error += undeploy_UserTestHome("UserTestHome");
    error += undeploy_SuperTestHome("SuperTestHome");
    error += undeploy_SuperTestHomeMirror("SuperTestHomeMirror");
    if(error)
    {
        cerr << "TEARDOWN ERROR: Can't undeploy component homes!" << endl;
        return error;
    }
    cout << ">>>> Stop Test Client: " << __FILE__ << endl;
}
