/**
 * This file was automatically generated by CCM Tools 
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_LoginImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package application; 

   
/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class ServerloginImpl 
    implements CCM_Login
{
    /** Reference to the facet's component implementation */
    private ServerImpl component;

    public ServerloginImpl(ServerImpl component)
    {
        this.component = component;
    }

    /** Business logic implementations */

    public boolean isValidUser(PersonData person)
        throws Components.CCMException, InvalidPersonData
    {
        if(person.getName().length() == 0)
            throw new InvalidPersonData();
        
        if(person.getId() == 277
                && person.getName().equals("eteinik")
                && person.getGroup() == Group.USER)
        {
            return true;
        }
        else
        {
            return false;
        }
    }    
}
