
/**
 * This file was automatically generated by 
 * <http://ccmtools.sourceforge.net/>
 * DO NOT EDIT !
 *
 * CCM_BasicTypeInterface facet class implementation. 
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 **/

#include <cassert>
#include <iostream>
#include <wx/utils/debug.h>

#include "SuperTest_basicType_impl.h"

using namespace std;
using namespace wx::utils;

namespace ccm {
namespace local {

SuperTest_basicType_impl::SuperTest_basicType_impl(SuperTest_impl* component_impl)
  : component(component_impl)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

SuperTest_basicType_impl::~SuperTest_basicType_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

short
SuperTest_basicType_impl::f1(const short p1, short& p2, short& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f1(p1,p2,p3);
}

long
SuperTest_basicType_impl::f2(const long p1, long& p2, long& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f2(p1,p2,p3);
}

unsigned short
SuperTest_basicType_impl::f3(const unsigned short p1, unsigned short& p2, unsigned short& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f3(p1,p2,p3);
}

unsigned long
SuperTest_basicType_impl::f4(const unsigned long p1, unsigned long& p2, unsigned long& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f4(p1,p2,p3);
}

float
SuperTest_basicType_impl::f5(const float p1, float& p2, float& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f5(p1,p2,p3);
}

double
SuperTest_basicType_impl::f6(const double p1, double& p2, double& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f6(p1,p2,p3);
}

char
SuperTest_basicType_impl::f7(const char p1, char& p2, char& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f7(p1,p2,p3);
}

std::string
SuperTest_basicType_impl::f8(const std::string& p1, std::string& p2, std::string& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f8(p1,p2,p3);
}

bool
SuperTest_basicType_impl::f9(const bool p1, bool& p2, bool& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f9(p1,p2,p3);
}

unsigned char
SuperTest_basicType_impl::f10(const unsigned char p1, unsigned char& p2, unsigned char& p3)
    throw (Components::ccm::local::CCMException)
{
    SmartPtr<CCM_BasicTypeInterface> inner = 
      component->ctx->get_connection_innerBasicType();
    return inner->f10(p1,p2,p3);
}

} // /namespace local
} // /namespace ccm
