#ifndef __BASIC_TYPE_ARRAY__IDL__
#define __BASIC_TYPE_ARRAY__IDL__

/*
 * Here we define vectors of basic type values
 */
 
typedef short 			ShortArray[10];	
typedef long 			LongArray[10];
typedef long long 		LLongArray[10];
typedef unsigned short 	        UShortArray[10];
typedef unsigned long 	        ULongArray[10];
typedef unsigned long long      ULLongArray[10]; 
 
typedef float 			FloatArray[10];
typedef double 			DoubleArray[10];
typedef long double             LDoubleArray[10]; 
 
typedef char 			CharArray[10];
typedef wchar     		WCharArray[10];
typedef string 			StringArray[10];
typedef wstring			WStringArray[10];
 
typedef boolean 		BooleanArray[10];
typedef octet 			OctetArray[10];	
typedef any 			AnyArray[10];
typedef Object			ObjectArray[10];

typedef fixed<9,2>              FixedArray[10];


/*
 * Here we define matrices of basic type values
 */
 
typedef short 			ShortMatrix[10][20];	
typedef long 			LongMatrix[10][20];
typedef long long 		LLongMatrix[10][20];
typedef unsigned short 	        UShortMatrix[10][20];
typedef unsigned long 	        ULongMatrix[10][20];
typedef unsigned long long      ULLongMatrix[10][20]; 
 
typedef float 			FloatMatrix[10][20];
typedef double 			DoubleMatrix[10][20];
typedef long double             LDoubleMatrix[10][20]; 
 
typedef char 			CharMatrix[10][20];
typedef wchar     		WCharMatrix[10][20];
typedef string 			StringMatrix[10][20];
typedef wstring			WStringMatrix[10][20];
 
typedef boolean 		BooleanMatrix[10][20];
typedef octet 			OctetMatrix[10][20];	
typedef any 			AnyMatrix[10][20];
typedef Object			ObjectMatrix[10][20];

typedef fixed<9,2>              FixedMatrix[10][20];
 
 
/*
 * Here, we define cubes of basic type values
 */

typedef short 			ShortCube[10][20][30];	
typedef long 			LongCube[10][20][30];
typedef long long 		LLongCube[10][20][30];
typedef unsigned short 	        UShortCube[10][20][30];
typedef unsigned long 	        ULongCube[10][20][30];
typedef unsigned long long      ULLongCube[10][20][30]; 
 
typedef float 			FloatCube[10][20][30];
typedef double 			DoubleCube[10][20][30];
typedef long double             LDoubleCube[10][20][30]; 
 
typedef char 			CharCube[10][20][30];
typedef wchar     		WCharCube[10][20][30];
typedef string 			StringCube[10][20][30];
typedef wstring			WStringCube[10][20][30];
 
typedef boolean 		BooleanCube[10][20][30];
typedef octet 			OctetCube[10][20][30];	
typedef any 			AnyCube[10][20][30];
typedef Object			ObjectCube[10][20][30];

typedef fixed<9,2>              FixedCube[10][20][30];

#endif // __BASIC_TYPE_ARRAY__IDL__
