// $Id$

typedef sequence<string> StringSeq;
typedef sequence<StringSeq> StringSeqSeq;
typedef string StringArray[10];

component MyString
{
  attribute StringSeq seq1;
  attribute StringSeqSeq seq2;
  attribute StringArray array1;
  attribute string value1;
};

home MyStringHome manages MyString
{
};
