package ccmtools.JavaClientLib.templates;

import java.util.Iterator;
import ccmtools.JavaClientLib.metamodel.*;

public class InterfaceAdapterFromCorbaTemplate
{
  protected static String nl;
  public static synchronized InterfaceAdapterFromCorbaTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    InterfaceAdapterFromCorbaTemplate result = new InterfaceAdapterFromCorbaTemplate();
    nl = null;
    return result;
  }

  protected final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/*" + NL + " * This file was automatically generated by ";
  protected final String TEXT_2 = NL + " * <http://ccmtools.sourceforge.net>" + NL + " * ";
  protected final String TEXT_3 = NL + " * DO NOT EDIT!" + NL + " */" + NL + " " + NL + "package ";
  protected final String TEXT_4 = ";" + NL + "                 " + NL + "import org.omg.CORBA.*;" + NL + "" + NL + "/**" + NL + " * Interface adapter from CORBA to Java." + NL + " */" + NL + "public class ";
  protected final String TEXT_5 = "AdapterFromCorba" + NL + "    extends ";
  protected final String TEXT_6 = "POA" + NL + "{" + NL + "    /** Java reference to the local interface */" + NL + "    private ";
  protected final String TEXT_7 = " localInterface;" + NL + "\t" + NL + "    public ";
  protected final String TEXT_8 = "AdapterFromCorba(";
  protected final String TEXT_9 = " receptacle)" + NL + "    {" + NL + "        this.localInterface = receptacle;" + NL + "    }    \t";
  protected final String TEXT_10 = "    ";
  protected final String TEXT_11 = NL;
  protected final String TEXT_12 = NL + "}";

  public String generate(Object argument)
  {
    StringBuffer stringBuffer = new StringBuffer();
     InterfaceDef iface = (InterfaceDef) argument; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append( iface.generateCcmtoolsVersion());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(iface.generateTimestamp());
    stringBuffer.append(TEXT_3);
    stringBuffer.append( iface.getJavaNamespace() );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(iface.getIdentifier());
    stringBuffer.append(TEXT_5);
    stringBuffer.append(iface.getAbsoluteIdlName());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(iface.getIdentifier());
    stringBuffer.append(TEXT_7);
    stringBuffer.append(iface.getIdentifier());
    stringBuffer.append(TEXT_8);
    stringBuffer.append(iface.getIdentifier());
    stringBuffer.append(TEXT_9);
    
for(Iterator i=iface.getOperation().iterator(); i.hasNext();)
{
    OperationDef op = (OperationDef)i.next();

    stringBuffer.append(TEXT_10);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(op.generateOperationAdapterFromCorba());
    
}

    stringBuffer.append(TEXT_12);
    return stringBuffer.toString();
  }
}
