/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package application.ccm.local;
 
public enum Group 
{
    GUEST,
    USER,
    ADMIN
}
