/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package application.ccm.local;


 
public class PersonData 
     implements java.io.Serializable
{
    private static final long serialVersionUID = -7240361783509412936L;
    
    private int id;
    private String name;
    private String password;
    private Group group;

    public PersonData() 
    {
        setId(0);
        setName("");
        setPassword("");
        setGroup(null);
    }


    public PersonData(int id, String name, String password, Group group) 
    {
        setId(id);
        setName(name);
        setPassword(password);
        setGroup(group);
    }



    public int getId()
    {
        return this.id;
    }     

    public void setId(int value)
    {
        this.id = value;
    }


    public String getName()
    {
        return this.name;
    }     

    public void setName(String value)
    {
        this.name = value;
    }


    public String getPassword()
    {
        return this.password;
    }     

    public void setPassword(String value)
    {
        this.password = value;
    }


    public Group getGroup()
    {
        return this.group;
    }     

    public void setGroup(Group value)
    {
        this.group = value;
    }


}
