/*
 * This file was automatically generated by CCM Tools version 0.7.0
 * <http://ccmtools.sourceforge.net>
 * DO NOT EDIT!
 */

package application.ccm.local;

import java.util.logging.Logger;

import Components.ccm.local.CCMException;
import Components.ccm.local.CCMExceptionReason;
import ccm.local.ServiceLocatorException;
import ccm.local.ServiceLocator;    
                              
public class ServerHomeClientLibDeployment 
{
   /** Default logger instance */
    private static Logger logger = ServiceLocator.instance().getLogger();
    
    
    public static void deploy(String name)
        throws CCMException
    {
        logger.fine("name = " + name);
        try
        {
            Components.CCMHome remoteHome = ServiceLocator.instance().findCCMHome(name);
            ServerHome localHome = new ServerHomeAdapterToCorba(remoteHome);
            ccm.local.HomeFinder.instance().register_home(localHome, name);    
        }
        catch(ServiceLocatorException e)
        {
            throw new CCMException(e.getMessage(),CCMExceptionReason.SYSTEM_ERROR);
        }
    }

    
    public static void deployWithIor(String name, String ior)
        throws CCMException
    {
        logger.fine("name = " + name + ", ior = " + ior);
        org.omg.CORBA.Object obj = ServiceLocator.instance().getCorbaOrb().string_to_object(ior);
        Components.CCMHome remoteHome = Components.CCMHomeHelper.narrow(obj);
        ServerHome localHome = new ServerHomeAdapterToCorba(remoteHome);
        ccm.local.HomeFinder.instance().register_home(localHome, name);    
    }

    
    public static void undeploy(String name)
    {
        logger.fine("name = " + name);
        ccm.local.HomeFinder.instance().unregister_home(name);    
    }
}
