#ifndef __INTERFACE_FORWARD__IDL__
#define __INTERFACE_FORWARD__IDL__


interface Husband; // Forward declaration

interface Wife
{
     Husband getSpouse();
};

interface Husband
{
     Wife getSpouse();
};

#endif // __INTERFACE_FORWARD__IDL__
