/***
 * any test case
 *
 * This test case shows the usage of IDL basic and user types as parameters
 * in facet operations. 
 ***/

typedef sequence<any> AnyList;

struct Pair
{
  string name;
  any value;
};

interface AnyTest 
{
  any     op1(in any p1    , inout any p2    , out any p3    );
  AnyList op2(in AnyList p1, inout AnyList p2, out AnyList p3);
  Pair    op3(in Pair p1   , inout Pair  p2  , out Pair p3   );
};

component Test
{ 
  provides AnyTest test; 
};

home TestHome manages Test 
{ 
};

