
module world 
{

  interface IFace
  {
	/**
	 * Operations can be declared oneway if it is desirable for the caller to
	 * send a noncritical message to an object.
	 * Oneway operation invocations will use best-effort semantics!!!
	 * The caller will get an immediate return and cannot know for certain
	 * if the request has been invoked.
	 * 
	 * For obvious reasons there can be no "out" or "inout" parameters
	 * declared in oneway operatios. There must be no raises clause, and the
	 * operation must have a void return type.
	 */
    oneway void foo(in string str);
  };


  component Test
  {
    provides IFace port;
  };

  home TestHome manages Test
  {
  };

}; // /module world
