#ifndef __BASIC_TYPE_TYPEDEF__IDL__
#define __BASIC_TYPE_TYPEDEF__IDL__

/**
 * We can use typedef to create a new name for a type or to rename an 
 * existing type.
 */
 
 
/*
 * Here we define aliases for basic IDL types
 */
typedef short 		ShortType;
typedef long 		LongType;
typedef long long 	LLongType;
typedef unsigned short 	UShortType;
typedef unsigned long 	ULongType;
//typedef unsigned long long ULLongType; !!!	
	
typedef float 		FloatType;
typedef double 		DoubleType;
typedef long double     LDoubleType;

typedef char 		CharType;
typedef wchar     	WCharType;
typedef string 		StringType;
typedef wstring		WStringType;	

typedef boolean 	BooleanType;
typedef octet 		OctetType;	
typedef any 		AnyType;
typedef Object		ObjectType;

typedef fixed<9,2>      FixedType;


/*
 * Here we define aliases for existing typedefs
 */
typedef ShortType	MetaShortType;
typedef LongType 	MetaLongType;
typedef LLongType	MetaLLongType;
typedef UShortType	MetaUShortType;
typedef ULongType	MetaULongType;

typedef FloatType	MetaFloatType;
typedef DoubleType	MetaDoubleType;
typedef LDoubleType	MetaLDoubleType;

typedef CharType	MetaCharType;
typedef WCharType	MetaWCharType;
typedef StringType	MetaStringType;
typedef WStringType	MetaWStringType;

typedef BooleanType	MetaBooleanType;
typedef OctetType	MetaOctetType;
typedef AnyType		MetaAnyType;
typedef ObjectType	MetaObjectType;

typedef FixedType	MetaFixedType;


/*
 * Here we define aliases 2nd order...
 */
typedef MetaShortType	MetaMetaShortType;
typedef MetaLongType 	MetaMetaLongType;
typedef MetaLLongType	MetaMetaLongLongType;
typedef MetaUShortType	MetaMetaUShortType;
typedef MetaULongType	MetaMetaULongType;

typedef MetaFloatType	MetaMetaFloatType;
typedef MetaDoubleType	MetaMetaDoubleType;
typedef MetaLDoubleType	MetaMetaLDoubleType;

typedef MetaCharType		MetaMetaCharType;
typedef MetaWCharType	MetaMetaWCharType;
typedef MetaStringType	MetaMetaStringType;
typedef MetaWStringType	MetaMetaWStringType;

typedef MetaBooleanType	MetaMetaBooleanType;
typedef MetaOctetType	MetaMetaOctetType;
typedef MetaAnyType		MetaMetaAnyType;
typedef MetaObjectType	MetaMetaObjectType;

typedef MetaFixedType	MetaMetaFixedType;


#endif // __BASIC_TYPE_TYPEDEF__IDL__
