#ifndef __USER_TYPE_TYPEDEF__IDL__
#define __USER_TYPE_TYPEDEF__IDL__

#include<enum/Color.idl> 
#include<struct/Person.idl> 
 
/*
 * Here we define aliases for user defined IDL types
 */
typedef Color 			EnumType;
typedef Person 			StructType;


/*
 * Here we define aliases for existing typedefs
 */
typedef EnumType		MetaEnumType;
typedef StructType 		MetaStructType;


/*
 * Here we define aliases 2nd order...
 */
typedef MetaEnumType		MetaMetaEnumType;
typedef MetaStructType 	MetaMetaStructType;


#endif // __USER_TYPE_TYPEDEF__IDL__
