#include "ifaces/exc.idl"

#ifndef __OWUDB__AUTH_IDL__
#define __OWUDB__AUTH_IDL__

module owil {
module udb {

interface UserPassAuthentication {
   void auth_userpass(in string name, in string password)
   raises(NoSuchUser,
          InvalidPassword,
          DatabaseError,
          TerminalBlocked,
          UserBlocked,
          PasswordExpired);
};

};
};

#endif

