module owil {
module udb {

exception NoSuchUser {};
exception NoSuchLogin {};
exception NoDefaultLogin {};
exception InvalidPassword {};
exception DatabaseError {};
exception TerminalBlocked {};
exception UserBlocked {};
exception PasswordExpired {};

};
};
