#include "exc.idl"
#include "persdata.idl"
#include "logindata.idl"

#ifndef __OWUDB__LOGINMGR_IDL__
#define __OWUDB__LOGINMGR_IDL__

module owil {
module udb {

struct LoginResult {
   PersData pers;
   LoginData login;
};

interface LoginManager {
   LoginResult
   login(
      in string user,
      in string password,
      in string login)
   raises(NoSuchUser,
          NoSuchLogin,
          NoDefaultLogin,
          InvalidPassword,
          DatabaseError,
          TerminalBlocked,
          UserBlocked,
          PasswordExpired);
};

};
};

#endif

