#include "persdata.idl"
#include "exc.idl"

#ifndef __OWUDB__USERDBBROWSER_IDL__
#define __OWUDB__USERDBBROWSER_IDL__

module owil {
module udb {

interface UserDBBrowser {
   PersData get_user(in string name)
   raises(NoSuchUser,
          DatabaseError);
};

};
};

#endif

