/*  $Id$
*/


interface Point
{
    attribute double x;
    attribute double y;
    void move( in double dx, in double dy );
};


interface Line
{
    attribute Point startPt;
    attribute Point endPt;
    void move( in double dx, in double dy );
};


component Grfx
{
    provides Point point;
    provides Line line;
};

home GrfxHome manages Grfx
{
};
