
/**
 * This file was automatically generated by CCM Tools version 0.5.3-pre3
 * <http://ccmtools.sourceforge.net/>
 *
 * ccm::local::CCM_IFace facet class implementation. 
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 **/

#include <cassert>
#include <iostream>
#include <WX/Utils/debug.h>

#include "Test_iface_impl.h"

using namespace std;
using namespace WX::Utils;

namespace ccm {
namespace local {
namespace component {
namespace Test {

iface_impl::iface_impl(
    ccm::local::component::Test::CCM_Test_impl* component_impl)
  : component(component_impl)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

iface_impl::~iface_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

long
iface_impl::foo(const std::string& msg)
throw(::ccm::local::Components::CCMException,
        ccm::local::FatalError,
        ccm::local::SuperError,
        ccm::local::ErrorException )
{
    if(msg == "Error") {
        ErrorException error;
        ErrorInfoList errorInfoList;
        ErrorInfo errorInfo1;
        errorInfo1.code = 7;
        errorInfo1.message = "First error";
        errorInfoList.push_back(errorInfo1);

        ErrorInfo errorInfo2;
        errorInfo2.code = 13;
        errorInfo2.message = "Second error";
        errorInfoList.push_back(errorInfo2);

        error.info = errorInfoList;
        throw error;
    }
    else if(msg == "SuperError") {
      throw SuperError();
    }
    else if(msg == "FatalError") {
      FatalError fatalError;
      fatalError.what = "This is a fatal error condition!";
      throw fatalError;
    }
    else {
      cout << ">> " << msg << endl;
    }
    return msg.length();
}

} // /namespace Test
} // /namespace component
} // /namespace local
} // /namespace ccm
