/**
 * CCM Tools test case
 *
 * This test case shows the usage of nested interface
 * definitions. You can nest the following definitions
 * within the scope of an interface:
 *     - Constant definitions
 *     - Type definitions
 *     - Exception definitions
 *     - Attribute definitions
 *     - Operation definitions
 *
 * Note that you can't define an interface within another
 * interface.
 */

module world
{
  interface Test
  {
    struct portConnection
    {
      long id;
      string name;
    };

    typedef sequence <portConnection> portConnections;

    exception NotFound
    {
      string name;
    };

    portConnections get_connections();
  };
  
};
