
module wamas
{

struct Person 
{
  long id;
  string name;
};

typedef sequence<string> StringList;


interface VoidTypeInterface 
{
  void f1(in long p1);
  long f2();
};


interface BasicTypeInterface 
{
  long           f2(in long p1, inout long p2, out long p3);
  string         f8(in string p1, inout string p2, out string p3);
};


interface UserTypeInterface {
  Person     f2(in Person p1, inout Person p2, out Person p3);
  StringList f5(in StringList p1, inout StringList p2, out StringList p3);
};



component Test
{
  provides VoidTypeInterface  voidTypeIn;
  provides BasicTypeInterface basicTypeIn;
  provides UserTypeInterface  userTypeIn;

  uses VoidTypeInterface  voidTypeOut;
  uses BasicTypeInterface basicTypeOut;
  uses UserTypeInterface  userTypeOut;
};

home TestHome manages Test
{
};

}; // /module
