/**
 * include test
 *
 * We define the interfaces for facet, receptacles and component 
 * in separated files.  
 * The include statement is used to bring the files together.
 */

#include "Console.idl"

module world {

component Test
{
  attribute string prompt;

  provides Console console;
};

home TestHome manages Test
{
};

}; // end of module world
