/**
 * This file was automatically generated by CCM Tools version 0.6.3
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_Test component business logic.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */

package world.europe.austria.ccm.local;
   
/**
 * This class implements component equivalent and supported interfaces
 * as well as component attributes.
 * Additionally, session component callback methods must be implemented.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */   
public class TestImpl 
    implements CCM_Test
{
    /** Supported interface attribute variables */
    
    

    /** Component attribute variables */
     

    public world.europe.austria.ccm.local.CCM_Test_Context ctx;
    
    
    public TestImpl()
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }


    /* 
     * Supported interface methods 
     */

    /** Supported interface constants */
    
    
    

    /** Supported interface attributes */    
    
    
    /** Supported interface methods */
    public int foo(String msg)
        throws ccm.local.Components.CCMException, 
	       world.europe.austria.FatalError, 
	       world.europe.austria.SuperError, 
	       world.europe.austria.ErrorException
    {
        if(msg.equals("Error"))
        {
            world.europe.austria.ErrorException error =
                new world.europe.austria.ErrorException();
            world.europe.austria.ErrorInfo[] errorInfoList =
                new world.europe.austria.ErrorInfo[1];
            world.europe.austria.ErrorInfo errorInfo =
                new world.europe.austria.ErrorInfo(7, "A simple error!");
            errorInfoList[0] = errorInfo;
            error.info = errorInfoList;
            throw error;
        }

        if(msg.equals("SuperError"))
            throw new world.europe.austria.SuperError();

        if(msg.equals("FatalError"))
            throw new world.europe.austria.FatalError();

        return msg.length();
    }    
    


    /** Component attribute accessor methods */
    


    /** Facet implementation factory methods */
        

    /** Component callback methods */
    
    public void set_session_context(ccm.local.Components.SessionContext ctx) 
        throws ccm.local.Components.CCMException
    {
        this.ctx = (world.europe.austria.ccm.local.CCM_Test_Context)ctx; 
    }

    public void ccm_activate() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_passivate() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_remove() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }
}
