/*  $Id$
*/

interface BankAccount
{
    void deposit(in long amount);
    void withdraw(in long amount);
    long balance();
    long overdraftLimit();
    void setOverdraftLimit(in long newLimit);
};


component Bank
{
    provides BankAccount account;
};


home BankHome manages Bank
{
};
