/*  $Id$
*/


struct Point
{
    double x;
    double y;
};


interface Line
{
    attribute Point startPt;
    attribute Point endPt;
    void move( in double dx, in double dy );
};


component Grfx
{
    provides Line line;
};

home GrfxHome manages Grfx
{
};
