/******************************************************************************/
/*  Project: localPrototype (C++)                                             */
/*  File   : Display.idl                                                      */
/*  Version: 0.4                                                              */
/*  Date   : October 2002                                                     */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/


#include "ShowFacet.idl"


//==============================================================================
// Display Component
//==============================================================================

component Display
{
  provides ShowFacet show;
};

home DisplayHome manages Display
{
};
