/******************************************************************************/
/*  Project: localPrototype  (C++)                                            */
/*  File   : IntegerCalculator.idl                                            */
/*  Version: 0.4                                                              */
/*  Date   : October 2002                                                     */
/*----------------------------------------------------------------------------*/
/*  Company: SALOMON Automoation F&E                                          */
/*  Autor  : Egon                                                             */
/*----------------------------------------------------------------------------*/
/*  Note   :                                                                  */
/******************************************************************************/

#include "IntegerFacet.idl"

//==============================================================================
// IntegerCalculator Component
//==============================================================================

component IntegerCalculator
{
  provides IntegerFacet iUnit;
};

home IntegerCalcHome manages IntegerCalculator
{
};

