/**
 * Test case: facet exception 
 *
 */

struct ErrorInfo
{
  long code;
  string message;
};

typedef sequence<ErrorInfo> ErrorInfoList;

exception Error
{
  ErrorInfoList info;
};


exception SuperError{};
exception FatalError{};

interface Console {
  long println(in string msg)
    raises (Error, SuperError, FatalError);
};

component Test
{
  provides Console console;
};

home TestHome manages Test
{
};
