/*
 * This file was automatically generated by CCM Tools version 0.6.0
 * <http://ccmtools.sourceforge.net/>
 *
 * wamas::ccm::local::CCM_VoidTypeInterface facet class definition.
 */

#ifndef __FACET__wamas_ccm_local_voidTypeIn__H__
#define __FACET__wamas_ccm_local_voidTypeIn__H__

#include <wamas/ccm/local/VoidTypeInterface.h>
#include "Test_impl.h"

namespace wamas {
namespace ccm {
namespace local {
namespace component {
namespace Test {

class voidTypeIn_impl
    : virtual public wamas::ccm::local::CCM_VoidTypeInterface
{
  protected:
    wamas::ccm::local::component::Test::CCM_Test_impl* component;

    // This attribute is accessed by explicite set and get methods
    // which are part of VoidTypeInterface.
    long attr;

  public:
    voidTypeIn_impl(
        wamas::ccm::local::component::Test::CCM_Test_impl* component_impl);
    virtual ~voidTypeIn_impl();

    virtual 
    void 
    f1(const long p1) 
    throw(::ccm::local::Components::CCMException);

    virtual 
    long 
    f2() 
    throw(::ccm::local::Components::CCMException);

};

} // /namespace Test
} // /namespace component
} // /namespace local
} // /namespace ccm
} // /namespace wamas

#endif // __FACET__wamas_ccm_local_voidTypeIn__H__

