/**
 * This file was automatically generated by CCM Tools version 0.6.6
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_HelloImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world.ccm.local;

import Components.ccm.local.CCMException;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class HelloWorldhelloImpl 
    implements CCM_Hello
{
    /** Reference to the facet's component implementation */
    private HelloWorldImpl component;

    public HelloWorldhelloImpl(HelloWorldImpl component)
    {
        this.component = component;
    }
 


    /** Business logic implementations */

    public String sayHello()
        throws CCMException
    {
    	// TODO: IMPLEMENT ME HERE !
    	return "Hello world from inside the HelloWorld component!";
    }    

}
