// $Id$
/**
 * Test case: attribute_user_types
 *
 *
 */



// const double PI = 3.1415;

typedef long time_t;

enum Color {red, green, blue, black, orange};

typedef double doubleArray[10];

struct Record { 
  double x;
  float  y;
  long   z;
  string s1; 
  string s2; 
  string s3; 
}; 

typedef sequence<Record> RecordList;

component Hello
{
  attribute time_t typedef_value;
  attribute Color enum_value;
  //  attribute doubleArray array_value;
  attribute Record struct_value;
  attribute RecordList sequence_value;
};

home HelloHome manages Hello
{
};


