// $Id$
/**
 * Test case: attribute_user_types
 *
 *
 */

const float PI = 3.1415926;
const double twoPI = PI * 2.0; 

typedef long time_t;

enum Color {red, green, blue, black, orange};

typedef double doubleArray[10];

struct Value {
  string s;
  double d;
};

typedef sequence<Value> map;


component Hello
{
  attribute time_t typedef_value;
  attribute Color enum_value;
  attribute doubleArray array_value;
  attribute Value value;
  attribute map map_value;
};

home HelloHome manages Hello
{
};

