
/**
 * This file was automatically generated by CCM Tools version 0.5.3-pre3
 * <http://ccmtools.sourceforge.net/>
 *
 * ccm::local::CCM_IFace facet class implementation. 
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE! 
 *
 * @author
 * @version 
 **/

#include <cassert>
#include <iostream>

#include "Test_facet_impl.h"

using namespace std;
using namespace wamas::platform::utils;

namespace world {
namespace europe {
namespace ccm {
namespace local {

Test_facet_impl::Test_facet_impl(
    world::europe::ccm::local::Test_impl* component_impl)
  : component(component_impl)
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

Test_facet_impl::~Test_facet_impl()
{
    // OPTIONAL : IMPLEMENT ME HERE !
}

world::ccm::local::PDL_Person
Test_facet_impl::op1(
        const world::ccm::local::PDL_Person& p1,
        world::ccm::local::PDL_Person& p2,
        world::ccm::local::PDL_Person& p3)
throw(::Components::ccm::local::CCMException)
{
  cout << "p1.id        = " << p1.id << endl;
  cout << "p1.firstName = " << p1.firstName << endl;  
  cout << "p1.lastName  = " << p1.lastName << endl;

  cout << "p2.id        = " << p2.id << endl;
  cout << "p2.firstName = " << p2.firstName << endl;  
  cout << "p2.lastName  = " << p2.lastName << endl;

  p3.id = p2.id;
  p3.firstName = p2.firstName;
  p3.lastName = p2.lastName;
  
  p2.id = p1.id;
  p2.firstName = p1.firstName;
  p2.lastName = p1.lastName;

  world::ccm::local::PDL_Person result;
  result.id = p1.id;
  result.firstName = p1.firstName;
  result.lastName = p1.lastName;
  
  return result;
}

world::ccm::local::PDL_DTO
Test_facet_impl::op2(
        const world::ccm::local::PDL_DTO& p1,
        world::ccm::local::PDL_DTO& p2,
        world::ccm::local::PDL_DTO& p3)
throw(::Components::ccm::local::CCMException)
{
  cout << "p1.id               = " << p1.id << endl;
  cout << "p1.Person.id        = " << p1.person.id << endl;
  cout << "p1.Person.firstName = " << p1.person.firstName << endl;
  cout << "p1.Person.lastName  = " << p1.person.lastName << endl;

  cout << "p2.id               = " << p2.id << endl;
  cout << "p2.Person.id        = " << p2.person.id << endl;
  cout << "p2.Person.firstName = " << p2.person.firstName << endl;
  cout << "p2.Person.lastName  = " << p2.person.lastName << endl;

  p3.id = p2.id;
  p3.person = p2.person;
  
  p2.id = p1.id;
  p2.person = p1.person;

  world::ccm::local::PDL_DTO result;
  result.id = p1.id;
  result.person = p1.person;
  
  return result;
}

world::ccm::local::Other 
Test_facet_impl::op3(
        const world::ccm::local::Other& p1,
        world::ccm::local::Other& p2,
        world::ccm::local::Other& p3) 
throw(::Components::ccm::local::CCMException)
{

}

} // /namespace local
} // /namespace ccm
} // /namespace europe
} // /namespace world
