/**
 * Test case: facet user types 
 *
 */


//typedef long time_t;
//typedef double DoubleArray[10];

//enum Color {red, green, blue, black, orange};

struct Person {
  long id;
  string name;
};

//typedef sequence<long> LongList;
//typedef sequence<string> StringList;
//typedef sequence<Person> PersonList;


interface Console {
  long  f0(in long p1, inout long p2, out long p3);
  //  Color f1(in Color p1, inout Color p2, out Color p3);
  Person f2(in Person p1, inout Person p2, out Person p3);
  //  LongList f3(in LongList p1, inout LongList p2, out LongList p3);
  //  StringList f4(in StringList p1, inout StringList p2, out StringList p3);
  //  PersonList f5(in PersonList p1, inout PersonList p2, out PersonList p3);

  //DoubleArray f6(in DoubleArray a1, inout DoubleArray a2, out DoubleArray a3);
  //time_t f7(in time_t t1, inout time_t t2, out time_t t3);
};


component Test
{
  provides Console console;
};

home TestHome manages Test
{
};


