/**
 * This file was automatically generated by CCM Tools 
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_IFaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world;

import Components.CCMException;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class TestportImpl 
    implements CCM_IFace
{
    /** Reference to the facet's component implementation */
    private TestImpl component;

    public TestportImpl(TestImpl component)
    {
        this.component = component;
    }

    /** Business logic implementations */

    public int foo(String str) throws CCMException
    {
        System.out.println(">>> " + str);
        return str.length();
    }

}
