/**
 * This file was automatically generated by CCM Tools version 0.6.6
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_IFaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world.ccm.local;

import Components.ccm.local.CCMException;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class TestportImpl 
    implements CCM_IFace
{
    /** Reference to the facet's component implementation */
    private TestImpl component;

    public TestportImpl(TestImpl component)
    {
        this.component = component;
    }
 
    /** Business logic implementations */

    public int foo(String str)
        throws CCMException
    {
	System.out.println(">>> " + str);
	return str.length();
    }    

}
