/**
 * These types already exist as simle C structs. 
 * Thus, we define them as known any types.
 */
typedef any PDL_DTO;   // see impl/PdlAnyMappings.ccmany
typedef any PDL_Person; // see impl/PdlAnyMappings.ccmany
typedef any Other;

interface IFace
{
  PDL_Person op1(in PDL_Person p1, inout PDL_Person p2, out PDL_Person p3);
  PDL_DTO    op2(in PDL_DTO p1, inout PDL_DTO p2, out PDL_DTO p3);
  Other      op3(in Other p1, inout Other p2, out Other p3);
};

component Test
{
  provides IFace facet;
};

home TestHome manages Test
{
};

