// $Id$
/**
 * Test case: supports
 *
 */

interface Console {
  long println(in string s2);
};

interface Console2 {
  long println2(in string s2);
};

component Hello supports Console, Console2
{
};

home HelloHome manages Hello
{
};

