/**
 * This file was automatically generated by CCM Tools version 0.6.3
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_Test component business logic.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */

package world.europe.austria.ccm.local;

import world.europe.austria.*;
   
/**
 * This class implements component equivalent and supported interfaces
 * as well as component attributes.
 * Additionally, session component callback methods must be implemented.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */   
public class TestImpl 
    implements CCM_Test
{
    /** Supported interface attribute variables */
    
    

    /** Component attribute variables */
     

    public world.europe.austria.ccm.local.CCM_Test_Context ctx;
    

    // This attribute is accessed by explicite set and get methods
    // which are part of VoidTypeInterface.
    int attr;

    
    public TestImpl()
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }


    /* 
     * Supported interface methods 
     */

    /** Supported interface constants */
    
    
    

    /** Supported interface attributes */    
    
    
    /** Supported interface methods */

    public short fb1(short p1, ccm.local.ShortHolder p2, ccm.local.ShortHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return (short)(p3.getValue() + p1);
    }    

    public int fb2(int p1, ccm.local.IntegerHolder p2, ccm.local.IntegerHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() + p1;
    }    

    public short fb3(short p1, ccm.local.ShortHolder p2, ccm.local.ShortHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return (short)(p3.getValue() + p1);
    }    

    public int fb4(int p1, ccm.local.IntegerHolder p2, ccm.local.IntegerHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() + p1;
    }    

    public float fb5(float p1, ccm.local.FloatHolder p2, ccm.local.FloatHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() + p1;
    }    

    public double fb6(double p1, ccm.local.DoubleHolder p2, ccm.local.DoubleHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() + p1;
    }    

    public char fb7(char p1, ccm.local.CharacterHolder p2, ccm.local.CharacterHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return (char)(p3.getValue() + p1);
    }    

    public String fb8(String p1, ccm.local.StringHolder p2, ccm.local.StringHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() + p1;
    }    

    public boolean fb9(boolean p1, ccm.local.BooleanHolder p2, ccm.local.BooleanHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return p3.getValue() && p1;
    }    

    public byte fb10(byte p1, ccm.local.ByteHolder p2, ccm.local.ByteHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.setValue(p2.getValue());
        p2.setValue(p1);
        return (byte)(p3.getValue() + p1);
    }    





    public world.europe.austria.Color fu1(world.europe.austria.Color p1, 
					  world.europe.austria.ColorHolder p2, 
					  world.europe.austria.ColorHolder p3)
        throws ccm.local.Components.CCMException
    {
        p3.value = p2.value;
        p2.value = p1;
        return world.europe.austria.Color.orange;
    }    

    public world.europe.austria.Person fu2(world.europe.austria.Person p1, 
					   world.europe.austria.PersonHolder p2, 
					   world.europe.austria.PersonHolder p3)
        throws ccm.local.Components.CCMException
    {
        world.europe.austria.Person r =
            new world.europe.austria.Person(p1.id + p2.value.id, p1.name + p2.value.name);
        p3.value = p2.value;
        p2.value = p1;
        return r;
    }    

    public world.europe.austria.Address fu3(world.europe.austria.Address p1, 
					    world.europe.austria.AddressHolder p2, 
					    world.europe.austria.AddressHolder p3)
        throws ccm.local.Components.CCMException
    {
        Person pers = new Person(p1.resident.id + p2.value.resident.id, p1.resident.name + p2.value.resident.name);
        Address addr = new Address(p1.street + p2.value.street, p1.number + p2.value.number, pers);
        p3.value = p2.value;
        p2.value = p1;
        return addr;
    }    

    public int[] fu4(int[] p1, 
		     world.europe.austria.LongListHolder p2, 
		     world.europe.austria.LongListHolder p3)
        throws ccm.local.Components.CCMException
    {
        int[] result = new int[p1.length];
        p3.value = new int[p1.length];
        for (int i = 0; i < p1.length; i++)
        {
            result[i] = i;
            p3.value[i] = p2.value[i];
            p2.value[i] = p1[i];
        }
        return result;

    }    

    public String[] fu5(String[] p1, 
			world.europe.austria.StringListHolder p2, 
			world.europe.austria.StringListHolder p3)
        throws ccm.local.Components.CCMException
    {
        String[] result = new String[p1.length];
        p3.value = new String[p1.length];
        for(int i = 0; i< p1.length; i++)
        {
            result[i] = "Test";
            p3.value[i] = p2.value[i];
            p2.value[i] = p1[i];
        }
        return result;
    }    

    public world.europe.austria.Person[] fu6(world.europe.austria.Person[] p1, 
					     world.europe.austria.PersonListHolder p2, 
					     world.europe.austria.PersonListHolder p3)
        throws ccm.local.Components.CCMException
    {
        Person[] result = new Person[p1.length];
        p3.value = new Person[p1.length];
        for (int i = 0; i < p1.length; i++)
        {
            Person person = new Person(i, "Test");
            result[i] = person;
            p3.value[i] = p2.value[i];
            p2.value[i] = p1[i];
        }
        return result;
    }    

    public int fu7(int t1, ccm.local.IntegerHolder t2, 
		   ccm.local.IntegerHolder t3)
        throws ccm.local.Components.CCMException
    {
        t3.setValue(t2.getValue());
        t2.setValue(t1);
        return t3.getValue() + t1;
    }    




    public void fv1(int p1)
        throws ccm.local.Components.CCMException
    {
	attr = p1;
    }    

    public int fv2()
        throws ccm.local.Components.CCMException
    {
	return attr;
    }    
    


    /** Component attribute accessor methods */
    


    /** Facet implementation factory methods */
        

    /** Component callback methods */
    
    public void set_session_context(ccm.local.Components.SessionContext ctx) 
        throws ccm.local.Components.CCMException
    {
        this.ctx = (world.europe.austria.ccm.local.CCM_Test_Context)ctx; 
    }

    public void ccm_activate() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_passivate() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }

    public void ccm_remove() 
        throws ccm.local.Components.CCMException
    {
        // OPTIONAL: IMPLEMENT ME HERE !
    }
}
