
#ifndef __world_TEST__
#define __world_TEST__

#include "IFace.idl"

module world
{
    component Test
    {
      provides IFace iface;
    };

    home TestHome manages Test
    {
    };

}; // /module world

#endif
