package application;


/**
* application/ServerHome.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_ServerHome.idl
* Wednesday, August 16, 2006 12:56:54 PM CEST
*/

public interface ServerHome extends ServerHomeOperations, application.ServerHomeExplicit, application.ServerHomeImplicit
{
} // interface ServerHome
