package application;


/**
* application/ServerHomeExplicit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./idl2/application_ServerHome.idl
* Wednesday, August 16, 2006 12:56:54 PM CEST
*/

public interface ServerHomeExplicit extends ServerHomeExplicitOperations, Components.CCMHome, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerHomeExplicit
