// $Id$

typedef sequence<long> LongSeq;
typedef sequence<LongSeq> LongSeqSeq;
typedef double DoubleArray[10];

component MyBag
{
  attribute LongSeq seq1;
  attribute DoubleArray array1;
  attribute LongSeqSeq seq2;
};

home MyBagHome manages MyBag
{
};
