#ifndef __COMPONENT_ATTRIBUTE_USER_TYPES__IDL__
#define __COMPONENT_ATTRIBUTE_USER_TYPES__IDL__

#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>
#include <struct/Address.idl>
#include <array/BasicTypeArray.idl>
#include <sequence/BasicTypeSequence.idl>
#include <interface/InterfaceBasicTypeAttributes.idl>

component ComponentAttributeUserTypes
{
	attribute LongType typedefValue;
	attribute Color enumValue;
	attribute Address structValue;
	attribute LongArray arrayValue;
	attribute LongSeq sequenceValue;
  	attribute InterfaceBasicTypeAttributes interfaceValue;
};

#endif // __COMPONENT_ATTRIBUTE_USER_TYPES__IDL__
