#ifndef __COMPONENT_PUBLISHES__IDL__
#define __COMPONENT_PUBLISHES__IDL__

#include <events/EventtypeTest.idl>

component ComponentPublishes
{
  publishes Login login;
};

home ComponentPublishesHome
	manages ComponentPublishes
{
};

#endif // __COMPONENT_PUBLISHES__IDL__
