#ifndef __HOME_FINDER_METHODS__IDL__
#define __HOME_FINDER_METHODS__IDL__

exception SearchError
{
};

component HomeFinderMethods
{
    attribute string Id;
};

home HomeFinderMethodsHome
    manages HomeFinderMethods
{
    finder findComponent(in string name)
        raises(SearchError);
};

#endif // __HOME_FINDER_METHODS__IDL__
