#ifndef __HOME_FACTORY_USER_TYPES__IDL__
#define __HOME_FACTORY_USER_TYPES__IDL__


#include <typedef/BasicTypeTypedef.idl>
#include <enum/Color.idl>
#include <struct/Address.idl>
#include <array/BasicTypeArray.idl>
#include <sequence/BasicTypeSequence.idl>
#include <interface/InterfaceBasicTypeAttributes.idl>


component HomeFactoryUserTypes
{
    attribute string Id;
};

home HomeFactoryUserTypesHome
	manages HomeFactoryUserTypes
{
    factory createWithTypedef(in LongType id);
    factory createWithEnum(in Color id);
    factory createWithStruct(in Address id);
    factory createWithArray(in LongArray id);
    factory createWithSequence(in LongSeq id);
    factory createWithInterface(in InterfaceBasicTypeAttributes id);
};

#endif // __HOME_FACTORY_USER_TYPES__IDL__
