/**
 * This file was automatically generated by CCM Tools 
 * <http://ccmtools.sourceforge.net>
 * 
 * CCM_IFaceImpl facet implementation.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 * 
 * @author
 * @version
 */

package world; 

import Components.CCMException;
   

/** 
 * This class implements a component facet's methods.
 *
 * // TODO: WRITE YOUR DESCRIPTION HERE !
 *
 * @author
 * @version
 */
public class TestMirrormultiPort2Impl 
    implements CCM_IFace
{
    /** Reference to the facet's component implementation */
    private TestMirrorImpl component;

    public TestMirrormultiPort2Impl(TestMirrorImpl component)
    {
        this.component = component;
    }
 


    /** Business logic implementations */

    public int foo(String str)
        throws CCMException
    {
        System.out.println(">> multiPort-2: " + str);
        return str.length();
    }    

}
